### ISSUE TITLE
Shield Drop and Parry Changes [EXPERIMENTAL]

### ISSUE THREAD

**Issue by WuBoytH** [HDR-Development/HewDraw-Remix#1024]
A set of experimental shield changes that may or may not stay. Have an open mind and try them out (when they're ready) before casting judgement like Zeus on a bad day.

Shield Drop
Remove Shield + Taunt
Add Shield Release + Hold Down as a valid Shield Drop input. This lets you Shield Drop during the same window as jumping during Shield Release.

Parry
Remove Shield Release Parry
Make Shield + Special enter a specific Parry state, where the first 5 frames enable Parry. The next 20 frames are inactionable and will show your failure to parry something in your character's face of pure fear and terror.
For characters who do something on Shield + Special in vanilla, that will be moved to Shield + Taunt, the old Shield Drop input. Or something else, if you have a better idea.

**Comment by Riah321** [comment]
I'd personally like the idea to press shield and attack to parry, if possible.

**Comment by WuBoytH** [comment]
> I'd personally like the idea to press shield and attack to parry, if possible.

Riah that is literally grab.

**Comment by CrossSockDance** [comment]
> > I'd personally like the idea to press shield and attack to parry, if possible.
> 
> Riah that is literally grab.

I’m pretty sure this exact convo has happened before. Anyway yeah, the only way I see this realistically happening just due to the fact that Shield + Special for some characters is already a dedicated special mechanic for them is through either making a dedicated parry button or making a taunt button have even more use. The latter of which sounds cramped in practice.

**Comment by jdipalermo27** [comment]
I think taunt is the best option as there's no current reason to press both, beyond shield dropping, which is suggested to be removed in this post.
