### ISSUE TITLE
Cstick down fastfalls your aerials

### ISSUE THREAD

**Issue by EdgeGnW** [HDR-Development/HewDraw-Remix#1027]
Inputting cstick down in the air has the same effect as fully slamming your main stick down and pressing A. It seems the cstick press makes you fastfall. An example:

Falcon is on the 15th airborne frame of his short hop.

manual slight down + A lands on frame 31
cstick down lands on frame 23
manual full down + a lands on frame 23 too

I also tested Marth and Incineroar and found the same pattern.

It is very noticable for Marth since it is impossible get a dair out with the cstick after an instant shorthop fair.

**Comment by SergioC89** [comment]
I assume you use smash stick?

**Comment by EdgeGnW** [comment]
yes
I have confirmed this doesnt happen on tilt-stick

**Comment by ethangarsia517** [comment]
I'd like to add that in some circumstances, Smash Stick still gives you Tilt Attacks. I can provide replays for when it happens, but I haven't found an exact way to replicate it.

**Comment by blu-dev** [comment]
Will look into, ty
