### ISSUE TITLE
Mewtwo's Shadow Ball eaten up by the ground

### ISSUE THREAD

**Issue by skudo4president** [HDR-Development/HewDraw-Remix#1028]
https://user-images.githubusercontent.com/70296534/190428563-8109f8c0-f12a-4108-93ba-30349d154d12.mp4

https://user-images.githubusercontent.com/70296534/190428755-b0c4006b-7b12-4343-92a0-609e64decd85.mp4

**Comment by jobrien97** [comment]
Duplicate of #550
