### ISSUE TITLE
Character specific vars are accessed through different modules in opff and acmd, breaking some of their mechanics

### ISSUE THREAD

**Issue by JoaoAlmeida20** [HDR-Development/HewDraw-Remix#103]
Samus's shinespark doesn't work

I think this is because in samus's opff.rs the vars related to shinespark are accessed through the common module, like for example here:
https://github.com/HDR-Development/HewDraw-Remix/blob/dee2134137bc4d375ae899899b23a8064fecb45f/fighters/samus/src/opff.rs#L36

Meanwhile in the acmd script for dash attack the vars are accessed through the samus module, like for example here:
https://github.com/HDR-Development/HewDraw-Remix/blob/dee2134137bc4d375ae899899b23a8064fecb45f/fighters/samus/src/acmd/ground.rs#L12

**Comment by JoaoAlmeida20** [comment]
I didn't test Snake but it seems like he may have a similar issue looking at his code:
https://github.com/HDR-Development/HewDraw-Remix/blob/e32d9275144b37a3274b00453ae63c874025ba02/fighters/snake/src/opff.rs#L26

https://github.com/HDR-Development/HewDraw-Remix/blob/a7adc47c148f3a3430ee3323396e0861b5e39109/fighters/snake/src/acmd/specials.rs#L143

It's possible there are more characters with the same problem

**Comment by techyCoder81** [comment]
this will require looking through the VarModule common consts to see if there are any var names that are present in both common and individual character mods. In the example above, `SHINESPARK_READY` is defined in both `common` and `samus`. And the acmd is using one, but opff is using the other. There are very likely other instances of this issue.

Consts file:
https://github.com/HDR-Development/HewDraw-Remix/blob/f478ae3bcd1fb79f3360be64fe2b2a880c4c657c/dynamic/src/consts.rs
