### ISSUE TITLE
Spamming Tilt Stick Will Create Unregistered Inputs

### ISSUE THREAD

**Issue by Bortanian** [HDR-Development/HewDraw-Remix#1035]
There was something implemented with vanilla ultimate where if you use tilt stick and spam it the c-stick input will no longer register until it has returned to neutral for a time. The eating of inputs also happens when spamming an aerial and trying to transition into a tilt (falling uair > utilt).   I was curious if this is something that has been looked into. If changing it is possible that would be amazing.

This video explains the issue in vanilla ultimate better: https://youtu.be/XzMSHDlDUfc

**Comment by jobrien97** [comment]
duplicate issue
