### ISSUE TITLE
Joker's Arsene Redesign/Proposed Changes

### ISSUE THREAD

**Issue by blu-dev** [HDR-Development/HewDraw-Remix#104]
The following changes have been proposed and discussed amongst the developer team a long time ago and now that we have the structure to make them happen I will be listing them on this issue and begin implementation:

## Overview
Right now, the damage required to obtain Arsene has been increased in HDR from vanilla, and so without using Rebel's guard Joker can get Arsene at ~100% most of the time (in my own personal experience).

The proposed changes would allow Joker to charge Arsene by dealing damage (damage to charge conversion currently undecided) and also allow Joker to manually summon Arsene at the cost of some of the Arsene meter.

These changes would also shift up Joker's playstyle with Arsene by changing some core stats.

## Itemized List

- [x] Rebel's gauge is charged by dealing damage
- [x] Arsene is now manually activated.
    - [x] You can bring out Arsene when Joker is actionable by pressing special a second time during Rebel's guard
    - [x] You can hit-cancel normals into Arsene activation if you have at least half charge on the meter, although this drains 25% of the remaining meter
    - [x] Arsene no longer activates during when you get full meter
    - [ ] If you have full meter when manually activating Arsene you get rewarded with some small stat/power boosts
- [x] Arsene can be de-activated by double tapping down special again. This deactivation will have to be done during the start up of the new Arsene down special as described later.
- [ ] Modified Arsene specials
    - [ ] Wings of Rebellion is now chargeable, with the **completely** uncharged version being an airdash that can be canceled into aerials (both uncharged and charged variants will have higher startup)
    - [ ] Eigaon does not kill but will instead pull opponents closer to Joker to set up for combos
    - [ ] Gun Special, generally more mobility
        - [ ] Rainstorm has higher horizontal mobility and lower gravity/endlag
        - [ ] Gun spiral allows for a "slam" with a landing hitbox after a bit
        - [ ] The gun dodges will give Joker a slide that can be canceled into normals partway through for momentum
        - [ ] Regular gun special has higher startup but pops up for combos
    - [ ] Down special is transformed into Maeigaon (the counter is removed), which summons a multihit curse spire in front of Joker that leaves him slightly plus on hit against opponents
- [ ] Other changes
    - [x] Arsene activation can be B reversed if you summon Arsene during the start up of Rebel's guard
    - [ ] General speed/mobility *decrease* while Arsene is active and worse frame data on Arsene normals to compensate for the rework

**Comment by moklmaru** [comment]
Arsene mechanics reworked in https://github.com/HDR-Development/HewDraw-Remix/pull/105
