### ISSUE TITLE
Tapping up on float characters causes them to lose their float

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#1042]
When a character who has float taps up at any point of their jump in which they can fast fall (that is to say, the later half of their jump), they immediately lose the ability to float if they did not initiate it at that exact moment. 

https://discord.com/channels/659964948365049887/950979417004466196/1022559344430174229

**Comment by jobrien97** [comment]
Resolved in #1107
