### ISSUE TITLE
Adding fighters in HDR

### ISSUE THREAD

**Issue by Bibidimah21** [HDR-Development/HewDraw-Remix#1052]
In this mod Adds the Forgotten 4/5 Newcomers from Brawl Includes Plusle & Minun includes the induvidual variant, Toon Zelda, Tetra, Dixie Kong and Ayumi T. comes Better and Newcomers Fighters Toad, Toadete and Koopa Troopa comes better with HDR as 98 fighters.

**Comment by blu-dev** [comment]
rip bozo closing the issue

**Comment by elias-michaias** [comment]
he was ahead of his time

**Comment by Bibidimah21** [comment]
> he was ahead of his time

Going To be a issue label:enhancement!
