### ISSUE TITLE
Trying to finish classic mode with Kirby softlocks the game

### ISSUE THREAD

**Issue by sparkswordkirby** [HDR-Development/HewDraw-Remix#1071]
Bug: when you beat marx in Kirby's final stage, the fight doesn't end and you can no longer pause, closing the game is the only way out.

Small explanation cause I can't record it:
The stage you fight marx on now has a battlefield-esque variant over it instead, rather than the flat plain from the original.

Marx does not know what to do when he's under this stage, so he remains there indefinitely and can just be killed with 0 opposition but...

Killing him leaves him still unable to do finish his death animation, this leaving the game stuck with a frozen timer and an unpausable state. Kirby can't die either, there's no way out.

**Comment by moklmaru** [comment]
should no longer be relevant with boss stage layouts being removed
