### ISSUE TITLE
Pichu charge not granted by certain moves and bug in training mode

### ISSUE THREAD

**Issue by BrandonBSaysWhat** [HDR-Development/HewDraw-Remix#1082]
Of Pichu’s moves that are intended to give charge equivalent to the percent they deal, FSmash, Bair, and Dair have sort of issue with them. 
FSmash and Bair only award charge for the first hit of their multi hit, which does 2% (no staling). 
Landing Dair awards no charge, despite doing 4% (no staling).

When training mode is reset, Pichu’s charge amount is not reset. Additionally, if Pichu has charge and training mode is reset, Pichu keeps charge without a visual indicator, as if it had never been removed. Leaving training mode resets charge.

**Comment by H3ra-57** [comment]
Did a bit of testing of my own, just to confirm the charge issues:
- Fsmash and Bair charge on their first multihit as reported
- Dair does award charge, but the landing hitbox gives nothing. Not sure whether or not to keep it functioning this way

Currently there is no code handling training mode resets, should be an easy fix
Another Pichu PR is on the way, i'll fix these bugs with the buffs & changes
