### ISSUE TITLE
Bowser Jr can aerial glide toss during up special fall and go into a glitched kartless grounded state

### ISSUE THREAD

**Issue by JoaoAlmeida20** [HDR-Development/HewDraw-Remix#113]
Not sure if aerial glide tossing through neutral airdodging during up special fall was intended, but iirc it was not a thing before the refactor. Code responsible seems to be here https://github.com/HDR-Development/HewDraw-Remix/blob/e32d9275144b37a3274b00453ae63c874025ba02/fighters/koopajr/src/status.rs#L50
Either way doing this when you are close enough to landing will make it so that when you do land you do not get the clown kart back like you're supposed to. You still have close to full access to jr's grounded moveset but the kart is not there, and once you jump you will be in up special fall again. Once you have a regular up b landing you will get the kart back.
Clip: https://streamable.com/urf45w

**Comment by techyCoder81** [comment]
@jobrien97 what was the determination on what the intended behavior was for this? You mentioned that you knew what was wrong with this iirc

**Comment by JoaoAlmeida20** [comment]
There are still situations where the bug can occur:
https://streamable.com/rpgg0c
