### ISSUE TITLE
Sephiroth Going Through Stage 

### ISSUE THREAD

**Issue by stroderame** [HDR-Development/HewDraw-Remix#1158]
If you blade dash edge cancel and immediately go into b reverse octoslash, Sephiroth will clip through the stage if he holds a direction into the stage (2 videos attached). Uncharged will slightly clip through the stage but will always result in Sephiroth landing on stage (video of this is shown with me doing 75 degree angle).

https://user-images.githubusercontent.com/116753613/198100820-5616234f-42ae-4384-929e-9a5fb23aa756.mp4

https://user-images.githubusercontent.com/116753613/198101091-75fb8733-4efc-4654-aee4-900961f7f11c.mp4

https://user-images.githubusercontent.com/116753613/198101201-398c21d1-af17-4ca6-be17-f6caa1a8e5b3.mp4

**Comment by WuBoytH** [comment]
If this is on Nightly, there are issues currently with all ECBs. Please download the Pull Request build from here and try doing what you showed here.
https://github.com/HDR-Development/HewDraw-Remix/pull/1157
