### ISSUE TITLE
Game crashes after selecting stage using Ryujinx

### ISSUE THREAD

**Issue by impicto** [HDR-Development/HewDraw-Remix#1161]
Using Ryujinx, after opening the game and selecting a stage on the stage select screen, the game always freezes while loading the character select screen and crashes.

**Comment by zabimaru1000** [comment]
> Using Ryujinx, after opening the game and selecting a stage on the stage select screen, the game always freezes while loading the character select screen and crashes.

What does your game version say on Ryujinx? It should be on 13.0.1

**Comment by impicto** [comment]
oh yeah that was the issue, game was on 13.0.0
