### ISSUE TITLE
Aegis Recovery Bug

### ISSUE THREAD

**Issue by yoonikoo** [HDR-Development/HewDraw-Remix#1281]
When using Up B with Mythra, it is not possible to get it back until SHE specifically lands on the ground. If you Up B and switch to Pyra and land with Pyra, the landing does not refresh Mythra's recovery. This has been an ongoing issue for quite some time according to Aegis players.

**Comment by SuddyN** [comment]
I was unable to reproduce. Am I missing something?

https://user-images.githubusercontent.com/33226440/214195888-ac27cfb8-c56b-49f2-8dd1-a07a9cbe7dd9.mp4

**Comment by SuddyN** [comment]
In order to reproduce, must wait to switch to Pyra until after the end of the first phase of Mythra up special. Switching shortly after hitstun will not cause this bug

https://user-images.githubusercontent.com/33226440/214196340-e7f66f1a-628c-47db-96be-bca3ee575551.mp4
