### ISSUE TITLE
Jigglypuff falls through stage using rollout

### ISSUE THREAD

**Issue by TeamPearson** [HDR-Development/HewDraw-Remix#137]
I believe a full charge has to be used. I have a replay of this happening on one of the newest betas.

**Comment by TeamPearson** [comment]
https://discord.com/channels/659964948365049887/659979883631607829/942624994263969812
example video from maincord
suspected to happen on every stage
known instances have been on deadline, FD, and Yoshi's

**Comment by techyCoder81** [comment]
https://cdn.discordapp.com/attachments/659979883631607829/942624993697755146/2022021322221600-C6D726972790F87.mp4
