### ISSUE TITLE
HDR Crashes Instantly on latest Ryujinx build, (including Ryujinx LDN) whenever character loses a stock.

### ISSUE THREAD

**Issue by emufa** [HDR-Development/HewDraw-Remix#1384]

**Comment by O1yyy** [comment]
Please test if this issue happens in vanilla Ultimate, otherwise we will close this issue as its Ryujinx’s problem, not ours.

**Comment by Normality564** [comment]
Tested in vanilla, Doesn't crash when off screen

**Comment by Normality564** [comment]
This was fixed in the 1.1.621 update

**Comment by emufa** [comment]
Is it possible for this issue to stay open and logged by the HDR dev team? Even if fixed by Ryujinx, there are continual crashes on LDN, which will not be merged with mainline Ryujinx for some time, leaving Ryujinx netplay borderline unusable.

**Comment by Z0niC101** [comment]
this might be a related issue on your own build because this bug doesn't happen to any other ryujinx user I've seen, this also includes me.
