### ISSUE TITLE
salty runback works while in training mode

### ISSUE THREAD

**Issue by TeamPearson** [HDR-Development/HewDraw-Remix#149]
Using salty runback in training mode causes a bug where the training option menu stays up and is unable to be closed. Your only option is to exit training or close the game.

**Comment by techyCoder81** [comment]
the logic triggering salty runback needs to be guarded by a is_training_mode check, so that the logic isnt run in that context.

**Comment by blu-dev** [comment]
Disagree, salty runback should work in training mode it just shouldn't trigger the training mode menu.
