### ISSUE TITLE
Using some taunts on the respawn platform causes strange effects

### ISSUE THREAD

**Issue by LintyDX** [HDR-Development/HewDraw-Remix#1549]
^
Usually involving a Prop, object, etc sticking to the fighter's model.
So far, I've found this bug happens with:

Mario's Cappy Side-Taunt (kind of cool)
Dr. Mario's Pill Side-Taunt (does not reset upon death nor taunt)
Snake's Box Taunts (pretty funny, plus you can grab it while it's stuck to Snake.)
Bowser Jr.'s Down-Taunt (spawns a 2nd clown car)

Similar issues have also been found by 2 other users:
#713 
#502

**Comment by moklmaru** [comment]
moving issue #502 to be tracked here as well. Mega Man can go invisible if leaving the platform during down taunt

https://cdn.discordapp.com/attachments/660221487046852619/966399933999644772/megamanbug.mp4

**Comment by moklmaru** [comment]
Fixed by https://github.com/HDR-Development/HewDraw-Remix/pull/2293
