### ISSUE TITLE
Mii Bug when in Tourney Mode

### ISSUE THREAD

**Issue by XxBeanx** [HDR-Development/HewDraw-Remix#1552]
After entering my stages for the stage list feature in the launcher, I fully opened the game and went to edit one of my miis (I am picking up swordfighter). This action crashed the game three times in a row, and I am fairly confident it is the stage list feature as that is the only thing I have changed on my game since I last edited my miis the day before.
In the event the stages have something to do with it, the stages I chose are as follows:
Starters - 
Garreg Mach Monastery
Green Greens
Battlefield
Great Bay
Midgar

Counterpicks - 
Pokémon Stadium 3
Fountain of Dreams
Final Destination
Kongo Falls
Smashville

**Comment by Z0niC101** [comment]
This isn't a issue with the torny feature. It's just how the mii menu works. Go into training mode and PICK MARIO AS CPU and beat up up or idle for about 3-4 minutes 
Then back out normally and go to the main menu

**Comment by moklmaru** [comment]
resolved by #2020
