### ISSUE TITLE
Required fixes for 1.0.0-beta release

### ISSUE THREAD

**Issue by blu-dev** [HDR-Development/HewDraw-Remix#156]
- [ ] Issue #155 
- [ ] Issue #149 
- [ ] Issue #139 or equivalent
- [ ] Issue #103 
- [ ] Remove updater from official release, since it's not finished yet
- [ ] Move what we can to PRCX patch files (#73)
- [ ] Issue #71

**Comment by techyCoder81** [comment]
I may put this stuff in a project board/milestone later

**Comment by kalomaze** [comment]
the prcx change is in the latest nightly now
