### ISSUE TITLE
Additional costume slots (c08+) crash on the VS screen in HDR

### ISSUE THREAD

**Issue by Jetsplit** [HDR-Development/HewDraw-Remix#1564]
Currently using v0.26.100, I don't know if this is fixed in v0.30.45 but it's not mentioned in the changelog.

Following the standard process for adding additional slots in non-HDR Ultimate:

1. Ensure you have the newest ARCropolis release.
2. Copy the source slot (e.g. c01) to create a c08 for your fighter. Do this for all model folders, all motion folders, and all sound files for the fighter.
3. (Bonus step for HDR) Copy and paste the fighter's motion files from `hdr-assets` and replace those in your c08 folder.
4. Generate a config.json for the added slot using C#'s reslotter or CSK's website.

Anything past c07 is crashing on the VS screen. I'm having this issue with Banjo & Kazooie currently, and I've double checked both `hdr` and `hdr-assets` but I don't see any `buddy` files aside from the motion files in `hdr-assets`, nor do I see any mention of `buddy` in either folder's config.json. Although I've only tested with Banjo & Kazooie, there are multiple Gamebanana Question posts and messages in the HDR Discord from others having this issue with various other characters.

I'm hoping I'm just missing something, but I'm fairly certain this issue is HDR-specific and was introduced at some point after the nightly in which @WuBoytH fixed the Pokémon Trainer crashes, as I know for sure that I had additional slots working on that nightly version. For reference, below is my config.json (converted to .txt as GitHub wouldn't allow .json) for my extra Banjo slots:

[config.txt](https://github.com/HDR-Development/HewDraw-Remix/files/11278880/config.txt)

**Comment by WuBoytH** [comment]
Costume addition is not something we officially support, nor do I think it's worth investigating on an individual basis. Note this is coming from the guy who wrote the original guide on making added slots work with gameplay modpacks.

All I can say is if nothing of Banjo's files exist in config.json, you should not be including them with your costumes.

**Comment by Jetsplit** [comment]
Really sorry @WuBoytH and co., I was certain I had checked everything but after a few more rounds of trial and error I was able to get it working. Apologies for the non-issue!

**Comment by WuBoytH** [comment]
Not a problem, costume addition isn't simple (or stable) so stuff will fall through sometimes
