### ISSUE TITLE
"Arena" button on main menu sometimes doesnt work

### ISSUE THREAD

**Issue by alxndra0** [HDR-Development/HewDraw-Remix#1638]
If you change networks while HDR is open and then attempt to click "Arena"
instead of going to the flow with the "create lobby" and "join lobby" buttons
it will fade to black and then bring you back to the main menu.
the issue persists until restarting the game and then upon reboot.

**Comment by Ashtoric** [comment]
Not just switching networks. Turning your switch off does this as well, so say you turn your switch off for the night, and the next day you turn it on and try doing arenas, it won’t work like you say and you’ll need to restart. HDR seems to skip the in-game popup that says “connecting to the internet” or something from vanilla, which does it everytime the system is turned off.
