### ISSUE TITLE
Link grounded up-b is partially frozen when buffered out of landing lag

### ISSUE THREAD

**Issue by taythojulbra** [HDR-Development/HewDraw-Remix#1664]
The frozen anim can be canceled by pressing or holding b. Doesn't seem to happen if you are holding b.

https://github.com/HDR-Development/HewDraw-Remix/assets/81091452/e3e36676-21d1-458e-9659-f271168700e9

**Comment by jobrien97** [comment]
Fixed in latest Link PR
