### ISSUE TITLE
Training Mode Issues

### ISSUE THREAD

**Issue by kcucullen** [HDR-Development/HewDraw-Remix#1725]
I wanted to make a thread of every issue I find in training mode.

All of these are tested while using the training mod, but even if that's the cause, the training mod should be able to be used while in training mode.

So far: 

- Certain stages do not function as intended (i.e. Garreg Mach has incorrect collision and an extra right platform)

Will add more as I find them.

**Comment by Z0niC101** [comment]
Turn on stage haz in the settings if training mod pack

**Comment by moklmaru** [comment]
stages are intended to be played with hazards on; having them turned off causes strange effects such as that
