### ISSUE TITLE
Sonic UpB Snapping to Platforms

### ISSUE THREAD

**Issue by naptimehtx** [HDR-Development/HewDraw-Remix#1728]
https://github.com/HDR-Development/HewDraw-Remix/assets/115584147/70d9d239-f31e-4cb9-b550-eb0aa4691af8

Sonic's UpB Snaps to platforms with upb's landing lag when performed while passing through them

**Comment by Z0niC101** [comment]
This is probly has to do with the easy waveland platform tech
