### ISSUE TITLE
ken nair gives full meter on use

### ISSUE THREAD

**Issue by H3ra-57** [HDR-Development/HewDraw-Remix#175]
what it says on the tin. ken gets full meter for using nair

**Comment by black-calculus** [comment]
Identified the problem, the move adds 300 meter on hit (must have been left over from testing MeterModule): https://github.com/HDR-Development/HewDraw-Remix/blob/ecdb60bbe8f703eedcb734d4bdf22c19dd57ea32/fighters/ken/src/acmd/aerials.rs#L11

Should be an easy fix.
