### ISSUE TITLE
Stage names reverted to vanilla, msg_name not editable

### ISSUE THREAD

**Issue by MidRush** [HDR-Development/HewDraw-Remix#1774]
There has been a bug present for close to a year or so where the names of stages have been reverted to vanilla. For example, Pokemon Stadium 3 is displayed as Pokemon Stadium 2, and Deadline is displayed as Big Battlefield. 

Bizarrely, it is also not possible to edit the names manually as the msg_name file in hdr_stages > ui > message does not open MSBT Editor. Every other MSBT file still opens as normal.

**Comment by WuBoytH** [comment]
The msg_name file in `hdr_stages/ui/message` is an *xmsbt*, which is a file that only contains the changes from the vanilla msbt to our edited msbt. You can open that in any text editor.

If Bramble Blast and Ganon's Tower display as normal, then this should be an easy fix.
