### ISSUE TITLE
Shotos forgot how to rise with their Dragon Punches. 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#1890]
In the endless sea of bugs with the FGC characters, this glitch has been one of the more prevalent for a minute. Shotos will abruptly end their animation for a ground Shoryuken before even fully leaving the ground. I don’t know the how, but it can happen when on slants or moving platforms, this also leads to an animation glitch with Ken’s hand is ~suffering from Carpal Tunnel~ on fire constantly.

**Comment by zrksyd** [comment]
Yeah I consistently was able to do this on Summit. On the breakable ice slope.
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/6856627/ca24dcb8-4732-465a-8eb1-37d6c2b69258)
