### ISSUE TITLE
Jolt Haymaker does not slide as God intended. 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#1891]
When landing on the ground with Jolt Haymaker, Mac seems to cut all momentum and abruptly stop, not sliding with his momentum.

**Comment by jobrien97** [comment]
This is an intentional design choice from Vanilla, not a bug

**Comment by jobrien97** [comment]
It does not slide if you instantly trigger the attack off the ground.

**Comment by CrossSockDance** [comment]
I see, well okay then that’s a bit of a weird choice but whatever.
