### ISSUE TITLE
Terry SpecialLw Kinetic energy adjustment

### ISSUE THREAD

**Issue by blu-dev** [HDR-Development/HewDraw-Remix#19]
[Code in question](https://github.com/HDR-Development/HewDraw-Remix/blob/dev/fighters/dolly/src/acmd/specials.rs#L1360-L1555)

First of all, this file is nearly 2k lines long and I know that there isn't anything to do about that but let's see if we can resolve this

Second, this is probably a byproduct of the SaltySD/pre-skyline era where we didn't have a lot of options at our disposal. I am vehemently against leaving in hard-coded speed changes that happen on a per-frame basis. I'm not sure if we need to swap motion kinds for the EX moves instead of programming new functionality on top of the current ones (which this would be a more global change) but something has got to give because this is borderline unacceptable.

It should be noted that other speed changes (such as the speed boost during fire kick) I am OK with leaving in like this but we should really make a `ParamModule::get_vec2`, `ParamModule::get_vec3`, `ParamModule::get_vec4` helper functions for reading vectors out of a param file. Would make some of these more bearable

**Comment by black-calculus** [comment]
Sadly this is from the vanilla script as aggravating as it is but I am absolutely down to reimplement it in a better way
