### ISSUE TITLE
Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda

### ISSUE THREAD

**Issue by Bibidimah21** [HDR-Development/HewDraw-Remix#1905]
If Smash Brawl Unused newcomers reused in Smash Ultimate? 5 fighters Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda will joins in Smash Bros. Ultimate mod HewDraw Remix (HDR).

**Comment by SkewedAskew** [comment]
.makeit

**Comment by SuddyN** [comment]
new fighters are not planned

**Comment by Bibidimah21** [comment]
New fighters are planed for HDR

**Comment by Bibidimah21** [comment]
Reopen this

**Comment by Arlisbloxer05** [comment]
How about they don't? How about you finally leave people alone you oxygen-sucking black hole? We do not NEED you to be here.

**Comment by CrossSockDance** [comment]
If you don’t get your goofy-minded, smooth-brained, broke, worthless ass outta here…..

**Comment by Bibidimah21** [comment]
Why this Autumn update to add Fighters in HDR release?

**Comment by Arlisbloxer05** [comment]
> Why this Autumn update to add Fighters in HDR release?

### It isn't going to happen. Stop trying. Just because you see one fucking video doesn't mean it's going to happen. Get this through your thick skull, and fuck off already. You are contributing nothing to this community.

**Comment by Bibidimah21** [comment]
> 

Don't Angry people, Let to add fighers in HDR update release.
