### ISSUE TITLE
Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda Joins in HDR

### ISSUE THREAD

**Issue by Bibidimah21** [HDR-Development/HewDraw-Remix#1906]
If Smash Brawl Unused newcomers & Young Zelda used in Smash Ultimate? 5 fighters Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda joins in Smash Bros. Ultimate mod HewDraw Remix (HDR). Please Don't close issue.

**Comment by SkewedAskew** [comment]
.makeit

**Comment by JoBen-cmd** [comment]
![old-man-how-many-times-do-we-have-to-teach-you](https://github.com/HDR-Development/HewDraw-Remix/assets/78892309/ad00b032-09fd-47cc-b89d-e494fb38ec66)
