### ISSUE TITLE
Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda Joins the Battle

### ISSUE THREAD

**Issue by Bibidimah21** [HDR-Development/HewDraw-Remix#1908]
5 fighters Dixie Kong, Toon Zelda, Tetra, Plusle & Minun & Young Zelda will joins in Smash Bros. Ultimate mod HewDraw Remix (HDR). Includes Fighters spirits, Dixie Kong as Echo of Diddy Kong with Bubblegum Gun, Toon Zelda as Semi-Clone of Zelda, Tetra as Pseudo-Clone of Sheik, Plusle & Minun as Clone of Pikachu/Pichu Same size as Pikachu include Unique Side-B and Final Smash, Ice Climbers like & Young Zelda as Clone of Zelda. Expanding fighters in Super Smash Bros. Ultimate mod HewDraw Remix as best.

**Comment by CrossSockDance** [comment]
Not the racist trying to spam Hewdraw Remix

**Comment by Z0niC101** [comment]
And I thought I was annoying to hdr...

**Comment by Bibidimah21** [comment]
> And I thought I was annoying to hdr...

To be easly add fighters in HDR mod.

**Comment by Z0niC101** [comment]
![Screenshot_20230812_143230_TikTok](https://github.com/HDR-Development/HewDraw-Remix/assets/100329860/8f9b83ea-ee97-4baa-b39c-98033c970725)

**Comment by Riah321** [comment]
It's really reassuring to know I'm not the most annoying person to ever interact with the HDR community. Thank you.

**Comment by Z0niC101** [comment]
Me?

**Comment by Bibidimah21** [comment]
> Me?

Yes! In Super Smash Bros. Ultimate mod HewDraw Remix, adds 5 fighters to the game Dixie Kong (DK), Toon Zelda (Zelda), Tetra (Zelda), Plusle & Minun (Pokémon) & Young Zelda (Zelda) to the game. Works in Spirits's Adventure mode.

**Comment by Z0niC101** [comment]
Wasn't talking to you racist 😒

**Comment by Bibidimah21** [comment]
If 5 fighters adds in HDR mod for Super Smash Bros. Ultimate Like Dr. Mario, Mewtwo & Roy added/restored in SSBB's PM/P+ mod to be a better.

**Comment by H3ra-57** [comment]
We are not adding fighters to HewDraw Remix at this time. Even if we were adding fighters, we would not add the fighters you have mentioned. Stop opening up issues for this- it is not a place to make requests. If you do it again, there will be consequences.

**Comment by Bibidimah21** [comment]
> We are not adding fighters to HewDraw Remix at this time. Even if we were adding fighters, we would not add the fighters you have mentioned. Stop opening up issues for this- it is not a place to make requests. If you do it again, there will be consequences.

Sorry, You are develop to add the fighters to the mod HDR.
