### ISSUE TITLE
Small pikachu touch up

### ISSUE THREAD

**Issue by TeamPearson** [HDR-Development/HewDraw-Remix#1963]
Remove down air landing hitbox and effects associated with this hitbox

Reduce damage of bair from 14 to 12, and reduce bkb from 25 to 20

Restore F smash hitbox properties to vanilla 

Restored thunder projectile hitbox to vanilla values

Increase the consistency of forward air

Change up air to be more similar to melee pikachu up air

**Comment by moklmaru** [comment]
implemented in #2118
