### ISSUE TITLE
Japanese file is old

### ISSUE THREAD

**Issue by hiroki266** [HDR-Development/HewDraw-Remix#1998]
The Japanese file is old and the layout is broken.
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/73571045/91842ddd-845b-43a4-95bc-998eaa5fb467)
Use the following files if necessary
[+jp_ja.zip](https://github.com/HDR-Development/HewDraw-Remix/files/12817589/%2Bjp_ja.zip)

**Comment by O1yyy** [comment]
thank you! we’ll update the file, feel free to make updates to the file whenever possible!

**Comment by O1yyy** [comment]
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/19886440/e933f1db-c9f3-4b9b-9de7-905fc49843d8)
