### ISSUE TITLE
Arena Music stops when using added music

### ISSUE THREAD

**Issue by shun-one-1** [HDR-Development/HewDraw-Remix#2018]
Noticed this today. Was able to replicate it.

If an arena is using added music files any players who do not have it will have silent music. When initially joining the arena it will have whatever menu music persist. After a single round, music stops playing. I presume because it's searching for a file it does not have.

To replicate: 
Create Arena, set arena music to an added song not in base HDR.
any players who join the arena should have menu music at first
After 1 game and returning to the arena, music will stop playing

**Comment by WuBoytH** [comment]
This issue is not exclusive to HDR and is not our responsibility to fix.

A fix for this would more likely be included in Arcropolis, but I wouldn't hold my breath.

**Comment by shun-one-1** [comment]
Understood. I was uncertain if this was something that would have been covered by the fixes added to have series music play when custom music a player didn't have was being used.
