### ISSUE TITLE
Robin can still use Fire Jab when the Fire Tome is depleted

### ISSUE THREAD

**Issue by Eizzah21** [HDR-Development/HewDraw-Remix#2022]
[Test video made in 0.38.0, was also present in the update before]

https://github.com/HDR-Development/HewDraw-Remix/assets/81767857/d2b9f1b1-b062-4cb7-a5e8-083e7155cf4c

Robin can Fire Jab even when they have lost Fire Tome, and it will drop another Fire Tome.
I assume the intended behaviour would be for Wind Jab to override ?

**Comment by WuBoytH** [comment]
The correct behavior would be for Robin to perform Fire Jab, but with no hitbox or effects.

**Comment by WuBoytH** [comment]
nvm the correct behavior would be for jab 3 to not come out, apparently

**Comment by moklmaru** [comment]
Addressed by https://github.com/HDR-Development/HewDraw-Remix/pull/2495
