### ISSUE TITLE
Ganon float cancel bug 2

### ISSUE THREAD

**Issue by BusterMcNut** [HDR-Development/HewDraw-Remix#2071]
Canceling Ganon's float (both the down press and b press) cause him to fall faster than his regular fall speed.

https://github.com/HDR-Development/HewDraw-Remix/assets/145875695/2247aa8b-8767-4d29-8d79-0e31b152aea7

**Comment by blu-dev** [comment]
it's a buff to ur character u should be grateful

**Comment by BusterMcNut** [comment]
Should people not report issues on characters they play, or is there a misunderstanding here?
