### ISSUE TITLE
Corrupting Replays

### ISSUE THREAD

**Issue by Shmoovey** [HDR-Development/HewDraw-Remix#2114]
Whenever I save a replay and go watch it back, it will either:

"3,2,1, GO-" and then return back to the replays and say " this replay could not be played. Would you like to delete?"

or

The replay will play anywhere between 7-30 seconds, and then do the same thing. Already confirmed my sd card to be fat32 and everything. I know a few other individuals who also experienced the same thing. Lastly, I have not updated the game prior to trying to view my replays, so I would save the replay immediatley after the match, and then try to go watch it and the issue would occur.

**Comment by CrossSockDance** [comment]
Generally this will happen if the match you saved a replay from had a salty runback or you’re not on a version of HewDraw Remix that has the same properties as when the replay was made.

**Comment by Shmoovey** [comment]
> Generally this will happen if the match you saved a replay from had a salty runback or you’re not on a version of HewDraw Remix that has the same properties as when the replay was made.

Intersting; I'm unsure of what specifically would change, since in some cases, I've played one game(with no salty runback) saved the replay and then tried to replay it, and the same would happen. I wouldn't make changes to anything in between me saving the replay, and me watching the replay. I guess I'm just doomed 😭
