### ISSUE TITLE
Infinite loading screen 

### ISSUE THREAD

**Issue by CCMCrumb** [HDR-Development/HewDraw-Remix#2140]
On Yuzu, randomly when I select a character in online play, it loads infinitely before getting to the pregame training lobby and I don't know if I am doing something to cause it. It even happens in offline before it loads the VS screen.

**Comment by Z0niC101** [comment]
Go to the troubleshooting channel I'm sure you have something set up wrong @Zonic101(help if you need it).

**Comment by SkewedAskew** [comment]
This is reportedly fixed in the latest build of Yuzu
