### ISSUE TITLE
Wall jumping with tap jump wont work

### ISSUE THREAD

**Issue by CCMCrumb** [HDR-Development/HewDraw-Remix#2141]
When on the default wall jump controls with tap jump enabled, you still need to press a jump button to jump off walls.

**Comment by moklmaru** [comment]
Using tap jump to wall jump appears to work properly with the default wall jump setting of "Flick" (using default controls)

"Button" will not work, but that is due to the nature of holding into the wall and shouldn't be used with the intention of stick jumping
