### ISSUE TITLE
Zelda Usp sometimes crashes game

### ISSUE THREAD

**Issue by JaiChong** [HDR-Development/HewDraw-Remix#2148]
It isn't consistent; happened only 3 times over several hours at an offline event (Nightly 12/18/2023), on various setups.  I used her often at weeklies up until 11/07, took a break, then encountered it for the first time on 12/18.  I don't believe it has to do with the initial hitbox trade/clang, since one of the instances I recall was starting a combo using the initial hit (opponent was in hitstun).

![](https://github.com/HDR-Development/HewDraw-Remix/assets/46967996/4ec62ed5-f0fb-4a71-9f07-e35dd68f2db9)

This was recorded by an online opponent.  The freeze is always on the same frame on the Zelda setup before she reappears, whether offline or online (see comments below).

**Comment by Z0niC101** [comment]
Looks like it will only Happen when her upb gets interrupted or clanks

**Comment by JaiChong** [comment]
Froze maybe 5-10sec before.  This is the frame the game crashes on locally for the Zelda side, whether online or offline.  May have tried to cancel and would've gotten hit by the turnip, or may have tried to hit daisy with the full-length hitbox.  Can't recall.
![](https://github.com/HDR-Development/HewDraw-Remix/assets/46967996/f97d195e-7ee1-40ee-895b-50f13d478882)

edit: excuse my dog snoring lol

**Comment by JaiChong** [comment]
Locally froze for me before I reappeared, as previously described.  Switch online, recorded from friend's side:
![](https://github.com/HDR-Development/HewDraw-Remix/assets/46967996/bd2c45cf-0c3e-4f7a-8afc-e092954e6e0b)

**Comment by WuBoytH** [comment]
please provide a crash report if you want to see this fixed

**Comment by moklmaru** [comment]
Resolved by #2154
