### ISSUE TITLE
Olimar Side B to Down B in training mode

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#215]
If Olimar throws pikmin immediately upon respawning/resetting, and then pikmin recall, the red pikmin will specifically stay attached to the opponent for much longer and it will stay there doing nothing except breathing/expanding (It sounds strange but that's what it's doing). Please check Olimar channel to see a post of the issue with a video. It was posted by Mad Villain.

**Comment by techyCoder81** [comment]
in future if possible, a direct link to that post would be appreciated (right click, copy link in discord)

**Comment by blu-dev** [comment]
https://user-images.githubusercontent.com/42755519/157747023-db2ce751-cbd1-4365-a4cf-55de4a215cc4.mov

https://discord.com/channels/659964948365049887/660221182813011971/951275347779911721
