### ISSUE TITLE
This level in spirit mode crashes every time

### ISSUE THREAD

**Issue by Kommynct** [HDR-Development/HewDraw-Remix#2157]
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/13646790/b023516a-0b4a-42ac-8d0a-18756bd2ed81)

Let me know what I can do to log, but it is reproduced every time for me on emulator.

Works fine with the mod disabled.

**Comment by idontreallycareatall** [comment]
who cares

**Comment by chaosglory** [comment]
"Works fine with the mod disabled." 
Yeah, weird...

**Comment by Kommynct** [comment]
Sorry, I thought reporting bugs might be helpful
