### ISSUE TITLE
Pyra side b sometimes doesn't work as intended

### ISSUE THREAD

**Issue by Quackyyy** [HDR-Development/HewDraw-Remix#219]
Not sure why this happens but sometimes you get hit by the hitstun of the move but take no damage and it seems like it's a 50/50 chance to happen.

**Comment by blu-dev** [comment]
Can you get a video of it happening?

**Comment by blu-dev** [comment]
I did not mean to close this

**Comment by Quackyyy** [comment]
> Can you get a video of it happening?

Is there any way I can record this without a capture card?

**Comment by Quackyyy** [comment]
On the last hit the bowser jr is stuck in hitstun but not getting hit, and I'm not sure if this is intended.

https://user-images.githubusercontent.com/57575775/157764138-34615ae4-14f5-4541-9c09-f63446fa182c.mp4

**Comment by techyCoder81** [comment]
this can probably be fixed with some ACMD work.

**Comment by JazzGlobal** [comment]
> this can probably be fixed with some ACMD work.

I know this is old but I am interested in contributed. Can you elaborate on what ACMD is?

EDIT: Ah I think I understand. Each fighter seems to have an ACMD folder that looks to be responsible for tweaking attacks.

**Comment by SkewedAskew** [comment]
This is due to the move having a large amount of additional hitstun in vanilla to ensure the hits connected. This has long since been resolved in HDR

**Comment by JazzGlobal** [comment]
> This is due to the move having a large amount of additional hitstun in vanilla to ensure the hits connected. This has long since been resolved in HDR

Unfortunate. Thanks!
