### ISSUE TITLE
Toon Link sword texture missing

### ISSUE THREAD

**Issue by antisociable** [HDR-Development/HewDraw-Remix#220]
just a small issue of toon links sword texture is missing/see through 
![unknown](https://user-images.githubusercontent.com/93240026/157593317-dd9b28c3-81c3-4ac0-ac70-c327dcf3ffd8.png)
you can see through where the blade meets the hilt

**Comment by blu-dev** [comment]
I'm going to close this because that's a vanilla skin, and we haven't modified it. Not sure what could be causing this.
