### ISSUE TITLE
C Stick aerials will fast fall if inputted while holding down

### ISSUE THREAD

**Issue by Baltharaaz** [HDR-Development/HewDraw-Remix#221]
As the title states, any aerial performed at or after the apex of a jump whole holding down will automatically cause a fast fall as soon as the aerial begins. While useful in some cases, causes problems with Terry and Rising Tackle charge storage/canceling.

**Comment by SergioC89** [comment]
Isn't this vanilla behavior?

**Comment by jdipalermo27** [comment]
> Isn't this vanilla behavior?

I believe so, though it should still probably be changed.

**Comment by techyCoder81** [comment]
Honestly not sure if something like this is reasonably fixable, given how the cstick works. cc @blu-dev

**Comment by Riah321** [comment]
Has this been solved?

**Comment by jobrien97** [comment]
duplicate issue
