### ISSUE TITLE
Characters sometime slide backwards when dashing forward, no I don't mean moonwalking. 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#222]
From time to time I see my character (For the example, Terry) suddenly sliding the opposite way after I dash forward from landing, it's a very minute amount but in a mod attempting to be as precise as reasonably possible, this might cause issues with player's microspacing. I will update this later if I manage to recreate it again but it would most commonly occur for me on Pokemon Stadium 2.

**Comment by techyCoder81** [comment]
without more details this will most likely get closed at some point with `wontfix`

**Comment by blu-dev** [comment]
Can you provide a video and reproducibility steps please?

**Comment by CrossSockDance** [comment]
> Can you provide a video and reproducibility steps please?
I will be sending one here now. It's hard to see but I slid forward after landing but never pressed anything until I dashed back. 

https://user-images.githubusercontent.com/55810671/157833908-a36d6343-e1b3-47b9-a990-eb3af0cb21ad.mp4
