### ISSUE TITLE
reassess olimar now that development is easier

### ISSUE THREAD

**Issue by techyCoder81** [HDR-Development/HewDraw-Remix#223]
- [ ] whistle hitbox inconsistency
- [ ] pikmin attachment length
- [ ] purple shield damage/hitlag
- [ ] field a rock pikmin contribution?
- [ ] smash attacks
- [ ] consider making olimar slightly larger?
- [ ] make nair less hits / single hit?
- [ ] interesting dual hit uair, ala hodan?

**Comment by moklmaru** [comment]
Olimar has been reassesed!
