### ISSUE TITLE
Donkey Kong Barrel Indicator on Win Screen

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#225]
When Donkey Kong replenishes his ability to use barrel, he'll flash white briefly, but this also will occur on the results screen after the game.

**Comment by blu-dev** [comment]
This is likely just a modification to the gimmick timer code ensuring it doesn't play on the win screen (status kind win or status kind lose iirc)

**Comment by Kekker-git** [comment]
This affects Mario as well. Probably Sheik and YL too, but I haven't tested them.
