### ISSUE TITLE
Kirby does not inherit neutral special tech from other fighters' special moves

### ISSUE THREAD

**Issue by black-calculus** [HDR-Development/HewDraw-Remix#226]
The neutral special tech functions for Kirby were not ported over from the original (very first) repo (e.g. fast fall land cancel Fox/Falco laser, dash cancel Hero Frizz/Frizzle, etc., this should be addressed

**Comment by Riah321** [comment]
This issue has been consolidated alongside other Kirby neutral special issues. Please close it :)
