### ISSUE TITLE
C-stick ledge options all buffer attack

### ISSUE THREAD

**Issue by JaiChong** [HDR-Development/HewDraw-Remix#2279]
C-stick back is often used for ledge releases when inputting some harder melee/pm ledge tech, like Yoshi egg regrabs and hax dashes, etc., since it divides the difficult stick inputs up between two hands.  Would be nice to have for at least C-stick back, since I doubt anyone is specifically picking that direction intending for ledge attacks

**Comment by SuddyN** [comment]
Not an issue - this is a feature request. This feature is marked planned in the `game-feedback` forum channel on Discord
