### ISSUE TITLE
Mii Gunner Charge Shot Rework / Specials Tweak Suggestion

### ISSUE THREAD

**Issue by boondoggle621** [HDR-Development/HewDraw-Remix#2296]
I know the held melee attack was the way we've iterated it for now but I think that could better be suited to merge with current dark samus charge shot, but that's another issue. Given there aren't a ton of ways left to iterate charge shots, I propose a "boomerang" style charge shot, Magnet Shot. The projectile does not change y coordinates at all, so it isn't strictly a true boomerang. think holy cross but much weaker. As charge level increases, distance traveled prior to returning increases from short, medium, long. For visual clarity, projectile would change color as soon as it starts to decelerate into its return. Here's the extra wrinkle though: along the initial flight path, launch angle sends in, on the return path it would send out, converging the design and theme behind Gunner's charged aerials. There's some iteration to be had on flight speeds either increasing/decreasing on return flight as well as adjusting FC speed from where it's at so that it isn't oppressive. 

Other specials could use some tweaks for more functionality:
Flame Pillar: Wavebounce-able, and/or given an air dodge endlag cancel window akin to Wolf Laser, Popgun, etc
Bombs Away: larger explosion given how slow it is, and/or increased duration, or if neither, explode on clank.
Drop Bomb: Let Gunner hit (it)

**Comment by OneTrueJay** [comment]
I'm not a dev so take what I say with a huge grain of salt, but I'm close to 99% sure you're not supposed to submit design ideas/requests in the issues section. This is for real issues, bugs and the like. This is the kind of thing you'd send in a character channel inside the discord itself.
