### ISSUE TITLE
Super Happy Tree cloud platforms are still there.

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#230]
Super Happy Tree stage has a bunch of invisible platforms everywhere that disappear after use like in the vanilla version.

**Comment by techyCoder81** [comment]
Was this tested with hazards on or off? Our default is hazards on. Issues like this are common with hazards off, but we do not generally guarantee that hazards off will work well.

**Comment by jdipalermo27** [comment]
> Was this tested with hazards on or off? Our default is hazards on. Issues like this are common with hazards off, but we do not generally guarantee that hazards off will work well.

Hazards on, it seems a few stage have these invisible platform issues even with them on. Another one is the balloon on Great Bay may be showing up, but I need to test it more.

**Comment by Riah321** [comment]
Please close this issue has it has been addressed.
