### ISSUE TITLE
plat boosting in hdr engine

### ISSUE THREAD

**Issue by techyCoder81** [HDR-Development/HewDraw-Remix#231]
plat boosting would be a good addition to the hdr engine, This is basically momentum transfer during platdrop. This was originally suggested in twitch chat during a dev stream, and we felt that this would actually feel really nice if implemented correctly.

**Comment by techyCoder81** [comment]
after some discussion on it, the requirements would be:

- [ ] platdrop conserves momentum (uncapped)
- [ ] double jump conserves momentum if holding forwards

double jump momentum conservation is potentially controversial, may try it anyway

**Comment by jobrien97** [comment]
Was decided against after discussion
