### ISSUE TITLE
[Future Request] Play the game modes added in Ryujinx And Suyu

### ISSUE THREAD

**Issue by KeitoTobi1** [HDR-Development/HewDraw-Remix#2321]
In the current version, the added game modes are playable on the actual Switch device, but the added game modes are not playable on Ryujinx.

**Comment by Z0niC101** [comment]
You can't play game modes om ryujinx because ryujinx dosnt support web applet, however yuzu does. Use yuzu instead.

**Comment by KeitoTobi1** [comment]
Thx.

**Comment by KeitoTobi1** [comment]
I can no longer play on Suyu either.

**Comment by moklmaru** [comment]
Ryujinx support is an issue apart from the HDR dev team. Yuzu's inability to access extra game modes (which it used to be able to) is currently being tracked by https://github.com/HDR-Development/HewDraw-Remix/issues/2452
