### ISSUE TITLE
Move ledge occupancy logic out of OPFF and back to ledge functions, and change tether reel-ins to transition to trump when they attempt to grab an occupied ledge

### ISSUE THREAD

**Issue by black-calculus** [HDR-Development/HewDraw-Remix#235]
In the previous transition from C++ to Rust/Skyline, I moved the ledge grab function logic to the common OPFF to write in a hacky solution to ledge tethers not transitioning to trump when attempting to reel into an occupied ledge, which also affected ledge occupancy timings.

Specifically, due to the main function we used for OPFFs back in the C++ implementation of HDR (get_command_flag_cat) being run 4 times per frame, the game was able to check between frames whether or not to trump you as the tether character in the OPFF which caused no issues. However, now that we are using sys_line_control_system_fighter and the logic only runs once per frame, issues arose where tether characters would not be trumped properly, so I moved the ledge occupancy setting logic to where the OPFF logic for trumping you as the tether character reeling in to the occupied ledge was, and added a distance proximity window so you would be trumped before you actually reached ledge.

Now that we know a bit more about the game, we should place the ledge occupancy logic back into the ledge functions where they belong as well as add functionality to make tether reel-ins transition into ledge trump rather than ledge grab upon attempting to grab a ledge occupied as marked.

This should also resolve the issue where the player with the higher-numbered port will get trumped when multiple characters attempt to grab the ledge at the same time.

Related to issue #232 .

**Comment by black-calculus** [comment]
More specifically, the logic from `occupy_ledge()` `fighters/common/src/opff/ledges.rs` should be moved back into `fighters/common/src/function_hooks/ledges.rs` into the `entry_cliff_hook()` function as appropriate, and rewritten to remove the logic that was added to the implementation in the OPFF to behave properly there.

Additionally, `FIGHTER_STATUS_KIND_AIR_LASSO_REWIND` should transition into `FIGHTER_STATUS_KIND_CLIFF_ROBBED` instead of `FIGHTER_STATUS_KIND_CLIFF_CATCH_MOVE` / `FIGHTER_STATUS_KIND_CLIFF_CATCH` if the currently marked ledge they're trying to reel into is marked as occupied.

Let me know if assistance is needed in rewriting that if anyone gets to it first.

**Comment by Riah321** [comment]
Pretty sure this was addressed. Please close it if so  :)
