### ISSUE TITLE
Ike Arena Crash to Lobby/Non-registering Wall Jump issue

### ISSUE THREAD

**Issue by IkeMain2014** [HDR-Development/HewDraw-Remix#2389]
In online lobbies playing as Ike:
Trying to input Wall Jump after quick draw will result in crashing to lobby. I have found it only happens if on the "Button Jump" control set up. Can recreate fairly consistently, potentially a desync issue? Unsure, just an Ike player. Seems to happen more often when mashing the jump button after the quick draw Wall Jump. Stick Wall Jump after quick draw seems unaffected.

If done offline, I found I just don't get the Wall Jump to happen, just enter free fall. If on the button jump control scheme, I can still stick flick Wall jump, which seems incorrect. Appeared to happen more on the right side of the stage, but haven't tested extensively. Can recreate via video if needed.

**Comment by SuddyN** [comment]
resolved by https://github.com/HDR-Development/HewDraw-Remix/pull/2403
