### ISSUE TITLE
Rework floats

### ISSUE THREAD

**Issue by jobrien97** [HDR-Development/HewDraw-Remix#239]
- Completely rework float code (pull from Peach's float status)
- Create new status scripts/anims for floats
- Increase omnifloat speed + add acceleration/deceleration
- Make omnifloats consume double jump

**Comment by blu-dev** [comment]
The code for this was already rewritten (in lua, not rust) a while back by me, if that helps at all

**Comment by moklmaru** [comment]
Float code re-implemented by https://github.com/HDR-Development/HewDraw-Remix/pull/2298
