### ISSUE TITLE
Failed to Open Game

### ISSUE THREAD

**Issue by VtuberEnjoyer** [HDR-Development/HewDraw-Remix#2400]
I have no clue what happened, i opened HDR, and it failed to make in to the loading screen when i pressed play on the launcher. 
![image](https://github.com/HDR-Development/HewDraw-Remix/assets/103849518/0d1a7f3b-0f85-4bb3-80a3-86ff9311a8d0)

**Comment by Z0niC101** [comment]
Go to the hdr discord and in the channel #troubleshooting and I'll help you there.

**Comment by SuddyN** [comment]
resolved by manual troubleshooting
