### ISSUE TITLE
Game-Modes in ruleset menu do not work on emulator anymore.

### ISSUE THREAD

**Issue by Z0niC101** [HDR-Development/HewDraw-Remix#2452]
Using the game modes that are built into HDR such as Turbo, Hitfall, Air-Dash, Tag, etc. Do not work at all when trying to load the web applet. This Could be more so of an emulator error but I doubt it because the game modes in question worked in the last beta patch. The video is shown below

https://github.com/HDR-Development/HewDraw-Remix/assets/100329860/a6837111-e7c3-44d2-87a3-94a2873d52af

**Comment by Z0niC101** [comment]
and yes the controller is configured properly and does not miss-input.

**Comment by BrianAllred** [comment]
@moklmaru This was fixed in #2509
