### ISSUE TITLE
Lockout on non-once per airtime Fspecs OOH

### ISSUE THREAD

**Issue by JaiChong** [HDR-Development/HewDraw-Remix#2456]
I've experienced not being able to use F-specials out of hitstun that aren't once-per-airtime resources - Zelda's and Bjr's, possibly others.  Not sure of the cause, but it usually occurs 0-2 times per 2h session.  I have tried inputting additional times from drift after exiting tumble to be sure I didn't just buffer it too early, but it's def a lockout.  Can't recall if inputting DJ or AD fixes this or not, will try test next time I encounter it.

**Comment by JaiChong** [comment]
Found cause for Bjr at least - jumping out of aerial fspec.  Tested and AD, getting hit, and Usp + getting hit do not refresh the fspec.

**Comment by JaiChong** [comment]
https://github.com/HDR-Development/HewDraw-Remix/assets/46967996/d03f34a0-6792-47bb-b433-0a12a5d76cbf

**Comment by SuddyN** [comment]
BJr behavior resolved by https://github.com/HDR-Development/HewDraw-Remix/pull/2502

Please create a new issue with video/reproduction steps for Zelda, or any others. One issue per bug is ideal
