### ISSUE TITLE
[BUG]: Game crashes on launch if trying to open on wifi that requires web portal auth and isn't authorized yet

### ISSUE THREAD

**Issue by jmynes** [HDR-Development/HewDraw-Remix#2459]
This bug occured while running the current build, `v0.44.30-beta`, on a Switch running `17.0.1|AMS 1.6.2|E`, with `hekate v6.0.7`
**Steps to replicate:**
1. Be connected to hotel wifi (or equivalent}, but not authenticated with the web portal
2. Try to launch HDR
3. Observe error message:

```ARCopolis has panicked at 'TlsConnector::connect: Handshake failed with the following result: 167547', L:\.cargo\git\checkouts\rust-native-tls-e1c2f7824b5e2733\f202fca\src\imp\nnsdk.rs:386:17```

The switch then tells me that my software has closed due to an error.

I have the TE Skin Pack and also Jaw Alert music pack installed, though I don't expect this contributes to the issue 

I was able to launch after forgetting the hotel wifi, it probably would've worked if I authenticated as well.

**Comment by WuBoytH** [comment]
This is likely just because you didn't authenticate with the network. Please disconnect from the network or authenticate and you should no longer have this issue.

**Comment by jmynes** [comment]
Yes, that's what I ended up doing, as I wrote in the OP

However, it either should fail to connect and then continue in offline mode, or a better error message should be shown

**Comment by WuBoytH** [comment]
This is a launcher issue and not a game issue so I'm going to close this for now.
