### ISSUE TITLE
Bramble Blast Lags when too much is going on 

### ISSUE THREAD

**Issue by Truthsinger** [HDR-Development/HewDraw-Remix#2464]
There’s been reports of Bramble Blast lagging when modded skins are involved, but there are other times the stage will make the game lag without modded skins. Examples are when Ken uses Shaku during his install a ton, Sephiroth manipulating multiple projectiles at once, etc. If there’s a way to optimize the stage I’d appreciate that, especially since the stage is very common in competitive play.

**Comment by SuddyN** [comment]
Bramble Blast has been updated to resolve this issue

If bramble blast continues to lag (offline, not emulator), please make a new issue
