### ISSUE TITLE
Little Mac's smash attacks can still cause blue zoom ins during edge cases

### ISSUE THREAD

**Issue by SergioC89** [HDR-Development/HewDraw-Remix#248]
Those edge cases being when he hits an opponent as he's being hit by non flinching attacks such as Fox's laser or Piranha Plant's poison. I'm not sure if I would consider it a bug per se but it's kinda weird that this stayed for a very specific scenario

**Comment by Riah321** [comment]
This issue has been addressed. Please close this issue :)

**Comment by SergioC89** [comment]
Should be reopened, it very much still occurs
