### ISSUE TITLE
Jumping out of Inkling’s aerial Roller spends your jump if you have it

### ISSUE THREAD

**Issue by KingBobbyG** [HDR-Development/HewDraw-Remix#2494]
Recently the change that required you to have your jump to cancel aerial Roller was reverted, meaning you can jump out of it whether you have your double jump or not. However if you do have your jump, jumping out of Roller spends it, unlike how it works in vUltimate where you’d keep your jump.

**Comment by SuddyN** [comment]
This is the intended behavior.
