### ISSUE TITLE
Luigi Misfire is guaranteed on the 6th Green Missile or earlier, not the 8th

### ISSUE THREAD

**Issue by cynidea** [HDR-Development/HewDraw-Remix#2500]
I performed an experiment where I repeatedly used Luigi's side special until I got a total of 100 Misfires, and tallied up how many attempts it took for each one. Results are below:

![image](https://github.com/user-attachments/assets/5784ee89-988e-4d4d-bc03-5cf266ebac3a)

By the intended implementation, I should be seeing instances where Misfire occurs on the 7th or 8th side special, but no such instances ever occurred out of these 100 Misfires.

It is worth noting that I've entered this data into a [chi-square calculator](https://www.graphpad.com/quickcalcs/chisquared1/), which did not find this distribution statistically significant when assuming a 1/6th expected chance for each category. 

So if you really wanted to, you could just not touch any code, declare this a simple buff to side special, and call it a day. :^)

**Comment by SuddyN** [comment]
Good catch. It seems that the code for calculating misfire fails our assumptions in two ways
- the range for random is exclusive, not inclusive
- the result is truncated by 1

What this means is that in reality a range of 7 numbers is generated (not 8), and then that is shifted down to 6. The actual odds (for now) are:
- 1st: 2/7
- 2nd: 1/7
- 3rd: 1/7
- 4th: 1/7
- 5th: 1/7
- 6th: 1/7

This makes the misfire guaranteed in 6, and biased toward 1st try (twice as likely).

**Comment by jobrien97** [comment]
Fixed in v0.47.0 pre-release
