### ISSUE TITLE
Airdodge is sometimes not restored (or possibly even taken?) when being hit during certain tech chase situations.

### ISSUE THREAD

**Issue by OneTrueJay** [HDR-Development/HewDraw-Remix#2521]
Below are two examples of this bug. It's happened to me several times, but these are the only 2 I can confidently say without a shadow of a doubt were not me simply dropping my input, that also happened on my own setup so I was able to record. After the double jump in both clips I pressed airdodge basically the entire time I was falling, mashing it all the way to the blastzone. And both times nothing came out. 

https://github.com/user-attachments/assets/c83f82c9-ac5e-4702-baea-1db242e32081

https://github.com/user-attachments/assets/963c570b-e62f-43be-826a-6021cb8fd4c1

**Comment by jobrien97** [comment]
Fixed in v0.47.0 pre-release
