### ISSUE TITLE
Bowser charged side smash animation reverting to dropkick stance.

### ISSUE THREAD

**Issue by LaughingGhost96** [HDR-Development/HewDraw-Remix#2539]
Randomly when I boot up HDR, If I go into a match or practice mode with Bowser and charge his side smash, it'll play the ever start of the punch wind up before reverting to his charged dropkick animation, when letting go, it'll go back to being the punch animation. I have other mods and noticed this when I was testing voice replacement mods for Bowser and other characters but I'm not sure if it's related to the issue. Sometimes this will happen, but other times it'll play out the normal punch when freshly booting up the mod.

**Comment by RayanBounab268** [comment]
Do you have any skin mods installed for Bowser? Because that can happen if there are conflicting animation files between HDR and the skin in question.

**Comment by LaughingGhost96** [comment]
Yes, I've deleted everything for the skins (such as effects) except for the
skin itself, the ui and sound files for voices. It's kinda odd, I have the
same thing for Mega Man but his new charged smash has never bugged out. I
tested him alongside Bowser with every new thing I added to each character
to see if it ever happened to him too. Do you think I should just leave
Bowser with no modded skins?

**Comment by OneTrueJay** [comment]
This is more of a question for the #troubleshooting channel in the HDR discord server. This part of the github is reserved mostly for actual bugs with the game, not mod conflicts.

**Comment by LaughingGhost96** [comment]
Okay thanks for letting me know, I'll go try that out, sorry for the inconvenience.
