### ISSUE TITLE
Dr mario buffs?

### ISSUE THREAD

**Issue by buffdrmario** [HDR-Development/HewDraw-Remix#2540]
Dr mario feels WAY too heavy, his reverse aerials didnt seem to come out at ALL for me, his down B tornado no longer goes high enough for me to hit an Up B attack BEFORE i land???  Go try in regular ultimate, dr mario can-with enough mashing- perform actions before landing off the higher tornado lifts. Its not an unrealistic mash either, i can consistently hit it in vanilla ultimate. 
      His neutral b is nothing, that freeze thing isnt viable, i would much prefer you put just vanilla boring pills in there over this. A much more interesting idea would be pills that do different damage and/or knockback coded to different colors, or elemental effect pills THAT STILL ARE RANGED? Some burst of ice in the immediate area in front of doc isnt that helpful considering people can get out of it rather quickly, i aint hittin no combos on that setup that are more worth it compared to a tornado or other attack. 
    I searched the forum, i think(idk how this site works), and i see ZERO dr mario issues reported. Wtf

**Comment by ethangarsia517** [comment]
I hope you're not consistently performing Neutral Specials by holding the Special button. Maybe try tapping it instead.

**Comment by H3ra-57** [comment]
Issues are for reporting bugs, not asking for buffs.

**Comment by buffdrmario** [comment]
Thanks for the quick reply. Sorry if i was a bit rude in my comment, but i
was disappointed for some various reasons, not just cuz of the mod's feel
but some other stuff too. Honestly it was my first time playin it, we did a
surprise tournament where i was informed halfway thru my set that theres no
'best of 3 matches,' we just doin one 3 stock round for some random prizes
kinda tournament. We spent a minute or 2 of the first stock just feelin it
out a bit, It was supposed to just be a fun time kinda thing but for me,
its got layers to why its makin me salty.....but thats still no reason to
be a dick, i was just around a bunch of people clownin on me and i was
upset at the time.

     As for "reporting a bug/requesting a buff/whatever the proper channel
is called," im sorry, im a noob to the whole thing, i said it in the
comment that i didnt know the site but i was also, perhaps, being a bit
douchey. I genuinely would like to work with someone on dr mario cuz im
probably one of the 3 dr mario solo mains (lol) whos been runnin doc since
he came out in melee. And i tried the search bar, i typed dr mario but saw
no results, but again idk how the site goes, if it takes some special extra
characters typed in to make the search right, or if i need to be really
specific, like, capital Dr and a period, Dr. Mario? Idk.

         If yall care to email me and get some feedback, id love to take
the time and talk about it, i dont understand how mods work and yall are
cool for makin one, so, idk how much work it is to tweak his stats but if
you want me to maybe watch a specific video or have a pointer for me to go
dip my toes and learn some lingo, id even take the time to learn the
physics and the mod stuff because eventually your mod may become more
commonplace at my locals, and i......would really like it if dr mario didnt
suck complete and total ass like he has for a few games now lol. I think he
was prob best in melee, and thats only cuz the roster was small enough for
him to keep up.

      Mainly id say currently, theres no quick dashing to reverse back
airs, even if its flick or slinshotted. Uh, idk if thats intentional but i
do that stuff sleeping in vanilla Ult. Its not even this hard in actual
Melee. I flick into back air and then I can air dodge, triple b-air, or
whatever, i can do actions in the small window before i hit the ground out
of a S.H. b-air. The weight of dr mario is much higher i take it, but
it......doesnt feel evenly distributed.
 If thats even possible?
 His jumping arcs are wack, unintuitive imo and i got thousands of melee
matches with doc, so, if you wanted him to feel good, the jumps gotta be
better. Idk exactly how to phrase this request, i dont know the lingo,
thats just my feel of it. Maybe his upwards acceleration isnt high enough,
sideways drift, something, idk. He feels like how piranha plant looks,
like, i felt like jumping with HDR Doc was like tossin a sack of potatoes
in the air in such a way that the sack spun, if that makes sense. His
aerial game just doesnt feel good either, even with reduced endlag. Even if
theyre speedy, a bunch of down air stomps  doesnt matter if the feel is
off. Doc was never super speedy on this area anyways unless you L cancel in
melee.  Or do whatever in Ult, use the appropriate move to shorthop and
'cancel the animation' to a tilt or something. Point is, this isnt
something id say was in the top 5 of "asks" if i were to ask for Doc
improvements. Never really felt like an issue when his attacks generally
had enough knockback to safely land without any fancy movement stuff. I
REGULARLY, in Vanilla Ultimate, use Docs Up B as an attack WAY more than
recovery cuz it has so much knockback that its seldom i get punished for
it. I often do what i call '3 frame trades,' where i get the up b initial
sweetspot out, but take an attack, and do none of my up b animation. Enemy
goes flying. Im already grounded and approaching.
Regularly.
If youre smart, doc is good, and id say i can "make him work" in Ult if i
reach my peak, but still, if we talkin shop? Lemme get uhhhh, better
recovery or some shit idk lol. Im editing this and realizing its way too
fckin long and im way past bedtime so gl readin this, i sincerely hope you
get what i mean and this isnt just a waste of time......its not like youre
a faceless corp, youre a talented group and maybe if we come together, i
could give some valid and heard input to affect change in a way thatd mean
a fair bit to me. Probably means nothing to yall, idk.

     As for the neutral b, i fully understood the difference in his new
attacks, i watched the video on the character differences for Docs stuff, i
think its neat and i applaud yall for doin anything neat at all, cuz he is
so stale by now. The pills tho, i think just using ice is limiting
yourself. He throws multicolored pills out. I always thought the first
thing anyone would consider is to make em do different things, like, damage
and/or knockback differences based on pill. Multicolored pills could be
removed entirely or just lumped together in one range(like, the differences
would be between red, blue, yellow, and any multicolor). You could just do
elemental pills, or even have some other status effects, it is medicine
after all. Sleep pills? Even if it was just a second or less, thatd be
epic. SPEED pills? Imagine your enemy getting the unexpected burst of
speed, you might think itd be to your own disasvantage but i think unless
your opponent specifically grinds that crap, theyll be wildly thrown off by
the timing change. Confusion pills? Reversed inputs i guess?
      Maybe thats asking too much. But then again, look at what a doc main
gotta put up with. Hero has a shitload of spells that do anything i
described, and more. They got sweet spots on the tips of other peoples
weapons, meanwhile no joke the clowns at nintendo got Docs sweetspots on
his wrist for his smash attacks? F-air sweetspot....exists? It cant just be
a consistent hit, like, its so committal it can be punished if it misses by
any good player, but nah. Sweet spot between 2 sours. Lots of people got
armor on their moves, but docs armor on the tornado is that first spin
before the whirl come out, and only for 10% attacks, and only on the
ground....

The list goes on, i mean its not like i want dr mario to be completely
different, id play someone else if i didnt want this character's style, but
he could use some developer help on things. And being told itd be sorta
like melee, and then its somehow worse feeling than any smash game ive
played doc in? Just really made me salty. Everyone else is like "omg,
wavedashing haha melee stuff," and im like....... "this isnt anything like
melee, where i got thousands of doc matches, or Ultimate, where ive been
grindin hard as hell the last year." Maybe thats just me, maybe im the only
one feelin disappointed with yalls dr mario rendition, if so i guess it
doesnt matter but still, if it becomes a common side event ill be very sad.
Ive been tryin to get melee to just BE a side event several times in my
life but everyones like "nah, play this other shit thats like Melee but
isnt," like for REAL? RoA, RoA2, Multiversus, DA SPUNCH BOP(spongebob)?
But not melee itself. The shit thats the main influence. I cant get a real
melee event goin, and idk, maybe its cuz between Ultimate being more
accessible and the whole "melee-like" genre, nobody's willing to even try,
and its sad. Yall like melee, yeah? Cuz If not, why bother attempting to
emulate the physics style? ( why wavedash, etc. ) Not tryin to get
philisophical but you ever think about this stuff? Im tryin to do somethin
way after the fact on the scene i guess, yall done had this out for years
now

**Comment by OneTrueJay** [comment]
Join the HDR discord, that's the place to discuss this, the github is for more official things, like actual bugs and releases. https://discord.gg/Fg4mwJtb 
I love discussing this game's meta, and will happily have a very long talk with you about HDR doc when you get there! I'm called ThaDeathJay, feel free to ping me!
