### ISSUE TITLE
Charizard Dair Landing Lag

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#280]
It is listed in the changelog that Charizard landing lag was increased from 13 to 14 frames, however, in game testing shows that landing lag is currently 24 frames.

**Comment by techyCoder81** [comment]
mention to changelog team, we dont manage that work

**Comment by MadVillainLordQ** [comment]
The issue is I'm not sure this is a changelog problem. Was it decided by developers to increase charizard dair landing lag by 10 frames or was it a mistake in making the change?

**Comment by black-calculus** [comment]
Reopening this ticket, the current landing lag is in fact a mistake
