### ISSUE TITLE
Shield Stun Modifier Global Increase

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#281]
There is no mention of the Shield Stun Modifier increase in the changelog and I think it's important enough to warrant mention about how moves are generally a lot safer on shield.

**Comment by techyCoder81** [comment]
this is an issue with the changelogs, for the changelog and wiki team, which we do not maintain. superjig is kinda in charge of that, but we've offloaded that workload to our community, especially with our new auto-changelogs.
