### ISSUE TITLE
Feature request: easy neutral attack controls option.

### ISSUE THREAD

**Issue by Apep-the-snek** [HDR-Development/HewDraw-Remix#299]
add an option to do neutral air whilst holding a direction on the control stick, this could be really useful if you use the c-stick for aerials, as then you won't have to release the control stick first to then do a nair, when you think about it, every other aerial doesn't have this problem, which is inconsistent with nair, it also makes it so that you can get full aerial drift with all aerials except nair, unless you do this which is super hard to do and i have tested it in hdr and it works https://www.youtube.com/watch?v=uLTx1MJ9bBk. i also have a secondary request with neutral attack (jab) and neutral special, but i think nair is the easiest to fix and the most useful.

**Comment by techyCoder81** [comment]
the only possible solution is cstick nair/cstick jab via diagonals

**Comment by Apep-the-snek** [comment]
well, it would be nice to do buffered idj nair with full drift (yes, that is useful in hdr too to get to certain y values consistently), but i guess not then. wouldn't c-stick nair/jab just become directional if you hold the control stick? i think it does in pm/+, not sure tho, even if it did, that's a very clunky way to do so, so i'll just close this issue with this comment..
