### ISSUE TITLE
Stacked Echo Fighters Setting is Bugged

### ISSUE THREAD

**Issue by CombatCactus** [HDR-Development/HewDraw-Remix#300]
### all echos appear pure white on the css when using the stacked echos option

![image](https://user-images.githubusercontent.com/82128515/158499368-dd34bbd1-0612-49f2-81e8-6634a7d05072.png)
![image](https://user-images.githubusercontent.com/82128515/158499476-eea4441f-160c-46fa-899d-7cc579a3e955.png)

**Comment by Riah321** [comment]
This has been addressed. Please close this issue :)
