### ISSUE TITLE
Dark Pit - Change orbitar hitbox startup to frame 5

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#304]
Change the startup of Dark Pit's guardian orbitar from frame 10 to frame 5 and fix left air startup declaration.

**Comment by MadVillainLordQ** [comment]
It's currently +6 on shield, so it can net a guaranteed grab with JC grab. Reducing its frame advantage to mitigate this should be looked into as well. My suggestion would be either +3 or +4 on shield.

**Comment by jdipalermo27** [comment]
> 

I will compare it to the other shines, but this seems to be a good thing to change as well.

**Comment by jdipalermo27** [comment]
> It's currently +6 on shield, so it can net a guaranteed grab with JC grab. Reducing its frame advantage to mitigate this should be looked into as well. My suggestion would be either +3 or +4 on shield.

I will compare it to other shine, but this is a good idea as well.

**Comment by MadVillainLordQ** [comment]
Unfortunately some of the other shines frame data is kinda crazy. I wouldn't look to compare it to those as they should most likely be nerfed as well.
