### ISSUE TITLE
Bug: attacks moonwalking you backwards

### ISSUE THREAD

**Issue by Apep-the-snek** [HDR-Development/HewDraw-Remix#306]
tested on nightly 24 and 26, cloud, joker, kazuya and the belmonts' down tilt, and bayonetta's side tilt move the character back during the move in a strange way, it's fun to play with, but you devs decide if this should be in or not. this happened on linux (arch) with high end amd computer specs

https://user-images.githubusercontent.com/33030702/158655155-b5aef24a-1fdd-4437-a207-c92d17eb07f0.mov

.

**Comment by jdipalermo27** [comment]
How are you doing this? Just down tilting?
