### ISSUE TITLE
Mining on 3D Land

### ISSUE THREAD

**Issue by theOnlyAitor** [HDR-Development/HewDraw-Remix#307]
Mining on the right side of the stage's dirt texture gives you iron, but the left side gives you dirt.

**Comment by theOnlyAitor** [comment]
I named it wrong my bad its on 3D land

**Comment by techyCoder81** [comment]
Ginn posted a fix for this, it needs to be integrated. https://discord.com/channels/659964948365049887/951219025751457862/954065738551947274

**Comment by O1yyy** [comment]
This can be closed, I have merged ginn’s fix to our romfs

**Comment by JoBen-cmd** [comment]
Please close this issue
