### ISSUE TITLE
Palutena Aegis Reflector nerfs

### ISSUE THREAD

**Issue by black-calculus** [HDR-Development/HewDraw-Remix#309]
Since this seems to be a hot button issue, figured I'd make a ticket specifically for addressing this currently absurdly broken prototype of a move

**Comment by theOnlyAitor** [comment]
some recommended changes, either make it hittable from anywhere or make it parryable, or even just make it move faster away with more endlag, any or all of these changes would be fine

**Comment by black-calculus** [comment]
- [x] Turn projectile reflection into absoprtion (multiply projectile lifetime by 0)
- [x] Increase startup and endlag, add more telegraphed effects
- [x] Add 15s cooldown
- [x] Remove reflection board proc on regular counter
- [x] Allow fighters to clank with the board (change clang/rebound type on the hitbox from ATTACK_SETOFF_KIND_OFF to ATTACK_SETOFF_KIND_ON)
- [x] Cause the wall to break upon colliding with another hitbox (in the weapon OPFF for WEAPON_KIND_PALUTENA_REFLECTIONBOARD, if we detect `AttackModule::is_infliction_status(boma, *COLLISION_KIND_MASK_ATTACK)`, transition the article to `WEAPON_PALUTENA_REFLECTIONBOARD_STATUS_KIND_BREAK`)
- [x] Decrease the shieldstun multiplier

Potential experimental changes to be explored in the future:
- Add a 'charge' mechanic where you store up a charge for the move by countering something successfully with the regular down special
- Reduce graphic and hitbox size to not be an 8ft tall block of menace
