### ISSUE TITLE
nok nok shell and snake items should only be available if items are turned on in the ruleset

### ISSUE THREAD

**Issue by techyCoder81** [HDR-Development/HewDraw-Remix#315]
mario and bowser (and anyone else) should not be able to pull nok nok shell
snake should not be able to pull smoke bomb or motion sensor bomb

ask blujay, he found a way to check if the items ruleset is turned on. should be simple

**Comment by Riah321** [comment]
This seems to be addressed. Please close this issue if that's the case :)
