### ISSUE TITLE
Drift DI affecting Vertical KB

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#316]
Drift DI in the current beta has a slight effect on vertical KB. 
Please see demonstration here:
[https://discordapp.com/channels/659964948365049887/950979364634382376/953710265176825936](url)

Blujay had submitted a fix and I verified it through my own testing.
[https://discordapp.com/channels/659964948365049887/950979364634382376/953711693278621746](url)

**Comment by Riah321** [comment]
Has this been addressed? If so please close this issue.
