### ISSUE TITLE
Random training mode crash as link

### ISSUE THREAD

**Issue by kalomaze** [HDR-Development/HewDraw-Remix#323]
![image](https://user-images.githubusercontent.com/66376113/158914310-23d7c8f0-6e6f-417a-9b23-af7266fe3b42.png)
![image](https://user-images.githubusercontent.com/66376113/158914346-17477916-eb10-445a-8cb7-5ef953a60c2d.png)

**Comment by techyCoder81** [comment]
this isnt really enough useful information to go by. could be anything.
