### ISSUE TITLE
Temporarily remove Lucina & Ganondorf idle animations

### ISSUE THREAD

**Issue by kalomaze** [HDR-Development/HewDraw-Remix#324]
Don't get me wrong, I like them, but idle replacements that don't sync with the rest of the moves look visually jarring after doing pretty much any grounded animation because it has to quickly snap back to the custom animation. In the future the rest of the grounded animations can be modified to accomodate for this but for now I feel they are the scraps of what hasn't been fully implemented and thus should stay out of the stable release

**Comment by techyCoder81** [comment]
Was there any kind of conversation about this? Won't be removed until there is.

**Comment by kalomaze** [comment]
Change denied a long time ago
