### ISSUE TITLE
Add alternative ways to execute shield drop / footstool / etc. besides taunt (for B0XX and Frame1 users)

### ISSUE THREAD

**Issue by zandm7** [HDR-Development/HewDraw-Remix#325]
B0XX and F1 users don't have a particularly easy way of accessing taunt (we have to press both mod buttons with our left thumb to turn the c-stick cluster into d-pad).

And since B0XX and F1 emulate a GCC, we also don't have enough inputs to simply map an unused button to taunt (and B0XX R1 doesn't physically have enough buttons for this in the first place).

For shield drop, I feel like it would be fine to make a diagonal down input while holding shield execute a shield drop, while also leaving the alternative option to press taunt to do the same thing. This keeps shield drop accessible to controller users who lost the controller lottery while also making it accessible to B0XX/F1 users (and PM/Melee players who don't want to learn a completely different input).

I'm not sure what to do about footstool; any suggestions?

**Comment by MadVillainLordQ** [comment]
Shield drop can also be executed using two shield buttons. Have you tried that method?

**Comment by techyCoder81** [comment]
Two shield buttons locks the shield in place. You can also just perform a shield drop like in melee/pm using a slow diagonal input.
As for footstool... you might have to ask the PM community what BOXX players do there, because they have taunt footstools as well.

**Comment by zandm7** [comment]
Two shield buttons works for shield drop, thanks for the tip!

As for footstool, it seems like R2 B0XX and Frame1 have an extra button that is mapped to D-Pad Up which can be used for footstool.

However, R1 B0XXes (i.e. mine) do not have these extra buttons.

Is there any chance we can work on an alternative method for footstooling?

**Comment by jdipalermo27** [comment]
There are two jump and two shield buttons by default, i would recommend remapping one of them to dpad up for the time being, but I believe I recall a mention of a controls menu change at some point.

**Comment by zandm7** [comment]
> There are two jump and two shield buttons by default, i would recommend remapping one of them to dpad up for the time being, but I believe I recall a mention of a controls menu change at some point.

Unfortunately that's not really viable on B0XX, both jump buttons and both shield buttons are actually needed for various reasons.

**Comment by jdipalermo27** [comment]
> > There are two jump and two shield buttons by default, i would recommend remapping one of them to dpad up for the time being, but I believe I recall a mention of a controls menu change at some point.
> 
> Unfortunately that's not really viable on B0XX, both jump buttons and both shield buttons are actually needed for various reasons.

I have a box controller, I understand why things are where they are, but if you wish to footstool, that's your option until a solution is brought up, it is possible to play box without one of the jump buttons, just harder. You could also use tap jump to replace the first row jump button, and while it may require some changing to your muscle memory, it is a viable way to play box and also remap the jump button to dpad up.

**Comment by zandm7** [comment]
Sure, I was just communicating that this should not be considered a permanent solution. AFAIK HDR is already planning to overhaul control scheme customization quite significantly, so hopefully additional options for footstooling are also being considered.
