### ISSUE TITLE
Crash during loading after CSS v0.3.36-nightly Package

### ISSUE THREAD

**Issue by JoaoAlmeida20** [HDR-Development/HewDraw-Remix#340]
Local match, Samus picked vs Random CPU
[01647729357_01006a800016e000.log](https://github.com/HDR-Development/HewDraw-Remix/files/8310259/01647729357_01006a800016e000.log)

**Comment by zandm7** [comment]
Just chiming in to say I don't have this issue on Ryujinx

**Comment by JoaoAlmeida20** [comment]
Likely some misinstall issues, a reinstall fixed it
Edit: Differences In the reinstall being I deleted an old smashline_development nro in disabled_plugins that had identical filename to the new one in plugins folder, and I deleted an odd unrelated g&w skins mod in ultimate/mods through hekate USB that was undeletable through FTP and that I thought could be causing trouble with the new arcropolis somehow
