### ISSUE TITLE
Kirby T-poses when using Sora's Neutral B - BUG

### ISSUE THREAD

**Issue by PumpkinSaga** [HDR-Development/HewDraw-Remix#346]
when ever i try to use Sora's neutral B as Kirby (freezes in both on ground and in the air) he just freezes in a T-pose until i get hit. my first time using git hub so idk how to use it verywell sorry if this is scuffed
![275802874_394357052040825_453794862609514965_n](https://user-images.githubusercontent.com/101989475/159174659-1213e045-83a7-4e6c-b559-65fd4f7204d2.jpg)

**Comment by cmargroff** [comment]
Sephiroth too HDR v0.6.29

**Comment by Riah321** [comment]
This issue has been consolidated with other kirby t pose issues. Please close this issue :)
