### ISSUE TITLE
wii fit studio crash on ryujinx with hdr-stages on

### ISSUE THREAD

**Issue by Jedi-Bob** [HDR-Development/HewDraw-Remix#36]
[Ryujinx_1.0.0b938bc5_2022-01-28_18-16-22.log](https://github.com/HDR-Development/HewDraw-Remix/files/7962662/Ryujinx_1.0.0b938bc5_2022-01-28_18-16-22.log)
happened after picking wii fit studio game crashed on loading into match

**Comment by blu-dev** [comment]
Please attach a screenshot of the title screen. Thanks

**Comment by Jedi-Bob** [comment]
![image](https://user-images.githubusercontent.com/78893114/151642441-57e6e1a0-aecd-4efe-ba7e-acd1ea364f96.png)

**Comment by blu-dev** [comment]
Thank you. Have you been able to confirm if this is also happens on console or have you only tested emulator thus far.

**Comment by Jedi-Bob** [comment]
![image](https://user-images.githubusercontent.com/78893114/151643011-630c0729-fc6b-4966-ab73-56fdadbe1c2b.png)

**Comment by Jedi-Bob** [comment]
i've only tested emulator so far but i'll probably have access to my switch tomorrow

**Comment by blu-dev** [comment]
Gotcha, sounds good. Which character were you playing?

**Comment by Jedi-Bob** [comment]
was lucina, clarified this was the issue in dev cord
