### ISSUE TITLE
Sora Neutral B issue (Nightly)

### ISSUE THREAD

**Issue by kalomaze** [HDR-Development/HewDraw-Remix#385]
In the latest nightly, Sora appears to be forced to jump during neutral b

https://user-images.githubusercontent.com/66376113/160252884-5c6d5abd-fc48-43a2-ae22-54cbd1c697a4.mp4

**Comment by jobrien97** [comment]
This is fixed in the upcoming Ground Movement PR (not just exclusive to Sora btw)
