### ISSUE TITLE
Hero's usmash ID 0 doesnt hit grounded opponents

### ISSUE THREAD

**Issue by O1yyy** [HDR-Development/HewDraw-Remix#411]
Hero usmash sucks on the ground cuz it has no pickup hitboxes, imo should be like Marths

BUT theres actually a hitbox that should be slightly scooping grounded opponents.. but isn't lol

![2022033002034200-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/19886440/160772109-87259191-ad39-41fb-a002-a512d1bc47f0.jpg)

**Comment by Riah321** [comment]
Pretty sire this is intended behavior. Please close this issue :)
