### ISSUE TITLE
Diddy Kong Up B Stall not working properly after being hit

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#433]
There is an issue with Diddy Kong's up B as he does not properly stall after getting hit by an opponents attack. He instead falls at the same acceleration he was in before he began his up B.

https://user-images.githubusercontent.com/101300494/161410981-6923bf49-5308-4cab-a0d2-1c03d18f8c20.mov

https://discordapp.com/channels/659964948365049887/660221119869091880/960026953652502528

**Comment by Angstdiscord** [comment]
Experienced this too.

**Comment by Riah321** [comment]
It's been adressed. Please close this issue :)
