### ISSUE TITLE
Tether ledgetrump works the opposite way it's supposed to

### ISSUE THREAD

**Issue by yordvandamme** [HDR-Development/HewDraw-Remix#439]
When I ledgehog characters with tethers in the new beta, I get ledgetrumped instead of them

**Comment by yordvandamme** [comment]
https://user-images.githubusercontent.com/86311241/161585865-40bf14e0-aef5-46a0-8b20-7d08e43bbe58.mp4

**Comment by techyCoder81** [comment]
Also, if ICs grab ledge, opponent can still grab ledge, and then popo got put into freefall off the ledge
