### ISSUE TITLE
Zair behavior request

### ISSUE THREAD

**Issue by Scorpio3002** [HDR-Development/HewDraw-Remix#444]
Can we possibly get Zair characters working like in PM? Currently, zair will trigger any time the Shield button is being held. PM ignores any "old" Shield input, so you can input an aerial out of shield or during a shield-drop without first releasing the trigger.

**Comment by Riah321** [comment]
~~This has been addressed in the new beta. Please close this issue :)~~
I lied. I hope this gets fixed soon

**Comment by moklmaru** [comment]
being tracked by #2115
