### ISSUE TITLE
PK Thunder 2 proposals

### ISSUE THREAD

**Issue by Scorpio3002** [HDR-Development/HewDraw-Remix#445]
I've documented the wallride/bonk behavior glitches, but I also wanted to document my old suggestions:

1) Make wallride be the default behavior, and allow Ness/Lucas to bonk with a Shield input.
2) Let Ness/Lucas be FULLY actionable after a bonk (able to airdodge, jump, aerial, etc). Limit 1 extra PK thunder off of a bonk per airtime (to prevent infinite stalling offstage), unless they take a hit, which refreshes it.

**Comment by quakcertsep** [comment]
Reducing the set knockback of lower priority pkt2 hits between the move 
![Screenshot_2022_0310_072935](https://user-images.githubusercontent.com/48404877/161983589-b502a06c-1659-4160-8f96-691df9835747.jpg)
as well
