### ISSUE TITLE
Knockback behavior readjustments

### ISSUE THREAD

**Issue by black-calculus** [HDR-Development/HewDraw-Remix#469]
- Adjust params for gravity-based additional launch speed as well as combo gravity/fallspeed for all characters as appropriate
 -  Increase tumble threshold so low percent knockback isn't sending into tumble quite as early and DI/active defensive options (jump, attack, airdodge, etc.) are more feasible escape tools at low-mid percent to help mitigate the rampant early tech situation problem

**Comment by kalomaze** [comment]
praise the lord
