### ISSUE TITLE
Arena Ferox platforms disappear.

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#474]
When playing on Arena Ferox on the ps2 layout, if both opponents go high above the platforms, the platforms will unload before the camera moves out of frame.

**Comment by Riah321** [comment]
Has this been addressed in the new beta?

**Comment by chrispo-git** [comment]
Still unaddressed, it seems like
https://user-images.githubusercontent.com/69305550/177046821-2b1f1c53-caf8-4ff7-b1ea-292e672c84da.mp4
