### ISSUE TITLE
Mii Brawler Crashes.

### ISSUE THREAD

**Issue by T7Lain** [HDR-Development/HewDraw-Remix#475]
Burning Drop Kick and Feint Jump both crash the game during their movement period.  Interestingly, hitting the opponent with Burning Dropkick before Mii Brawler starts moving doesn't crash the game.

**Comment by O1yyy** [comment]
All the issues you've opened are likely due to a faulty install, these are not present at all in the latest beta.

Join the discord and head to #help-questions to get your install checked, I will reopen the issues if you're in the Nightly for example, though you have not specified that yet.

**Comment by T7Lain** [comment]
Ah yes, I am using the nightly builds as of a few days ago

**Comment by T7Lain** [comment]
Well, there goes my sole reason for making a github account…

**Comment by O1yyy** [comment]
Hmm, have you tried hitting Verify on the launcher?
(thank you for playing hdr and making a github for this!)

**Comment by T7Lain** [comment]
I have, in fact verified my files. Nothing seemed corrupted or missing…

**Comment by O1yyy** [comment]
I see, I'll go ahead and test latest nightly aswell so we can confirm this together

**Comment by O1yyy** [comment]
All your character issues were debunked, latest 0.5.15 nightly has none of these.

Though your Arena Ferox issue is valid and known, it will be fixed next beta, thank you for submitting these regardless!

**Comment by T7Lain** [comment]
Well, I feel somewhat relieved that these weren’t overlooked issues but issues caused by me apparently not installing it the right way. Also, that arena ferox issue wasn’t submitted by me.
Feel free to delete my issue submissions.
