### ISSUE TITLE
Odd ECB missed tech issue

### ISSUE THREAD

**Issue by chrispo-git** [HDR-Development/HewDraw-Remix#484]
Certain things seem to trigger characters to have their missed tech effect play below the stage. Tested on FD and Training mode stage, and on Byleth and Marth.

https://user-images.githubusercontent.com/69305550/163483237-fd994bde-ee2a-4d40-ac04-f782de1f9c99.mp4

https://user-images.githubusercontent.com/69305550/163483243-6327528d-e1c7-4769-a493-b61e1eb1758f.mp4

https://user-images.githubusercontent.com/69305550/163483304-2684a474-c1a6-4c77-a545-cd311e8b1e75.mp4

https://user-images.githubusercontent.com/69305550/163483248-5fb8a603-53fa-4da5-a37a-1f359f35c98e.mp4

**Comment by blu-dev** [comment]
We do artificially shift up the ECB after being in the air 10 frames, that's like the cause of this. I'm going to mark it as aesthetic since it likely doesn't contribute to real problems in the game
