### ISSUE TITLE
Sonic Up-Tilt visual bug

### ISSUE THREAD

**Issue by Benn1005** [HDR-Development/HewDraw-Remix#504]
During the animations, most of Sonic’s facial expressions are still present, and they’re all over lapping, you probably won’t noticed it during gameplay, but it’s something I thought I should bring up anyway.

**Comment by BedeScarlet** [comment]
Yes, uptilt is a really old animation, back when you imported source engine files and expression editing was done through notepad. the animation should be cleaned up in general.
