### ISSUE TITLE
Robin Levin/Bronze Sword Changes and Fixes

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#546]
Robin's sword is a currently unintuitive in how it switches between levin and bronze states. It activates upon using a smash attack or smash input aerial, meanwhile bronze activates on tilt attacks, when levin loses charge, or when doing rising upair, but doesn't activate upon tilt aerials, nor any other rising aerial. Levin sword should only activate if a smash input occurs and bronze for tilt inputs, including aerials. The only time this doesn't apply is for nair, which should use levin if the last move used was levin, and bronze if bronze. This should also fix rising levin upair resetting the sword to bronze as it interferes with levin nair.

**Comment by jdipalermo27** [comment]
It was discussed that Robin would benefit from a smash and tilt attack specific button, but that would be a universal change and should be optional, Robin should still have this change regardless of the possibility of a smash button.

**Comment by jdipalermo27** [comment]
Other suggestions was making z aerial bring out bronze sword.

**Comment by Riah321** [comment]
Have these issues been addressed in the latest beta?

**Comment by jdipalermo27** [comment]
> 

No, there have been no robin changes as far as I'm aware.
