### ISSUE TITLE
Remove Pit Side Special Armor

### ISSUE THREAD

**Issue by jdipalermo27** [HDR-Development/HewDraw-Remix#547]
After discussion with some of the devs, it was acknowledged that Pit's side b should not both be jump cancellable and have armor.

**Comment by techyCoder81** [comment]
Please in future link this discussion here from discord.

**Comment by Riah321** [comment]
Please close this issue.

**Comment by jdipalermo27** [comment]
> Please close this issue.

Can you either link where this issue was solved or link the thread in which it was decided this change shouldn't happen?

**Comment by Riah321** [comment]
This section of the repo is supposed to be for bugs and things the developers are planning to change. Not for balance requests.
