### ISSUE TITLE
Crash on match start

### ISSUE THREAD

**Issue by novApostropheA** [HDR-Development/HewDraw-Remix#55]
game panics during matchup screen on latest nightly [https://cdn.discordapp.com/attachments/516484942142767105/937087111830585385/2022012914343300-1AB131B6E6571375B79964211BB3F5AE.jpg](url)

**Comment by blu-dev** [comment]
You are missing the romfs required. Please use the romfs provided in the test build zip.

**Comment by blu-dev** [comment]
Closing this now
