### ISSUE TITLE
when using terry down-b, it crashes the game.

### ISSUE THREAD

**Issue by MMM17213** [HDR-Development/HewDraw-Remix#589]
Terry's down b, for me at least, crashes the game when I use it. 

I did a complete reinstall of HDR, using 6.30 beta. 

Though I thought that the Sora PR changes were what was causing it, it just seems to be any variation of power dunk in the mot recent updates for the game.

Any help?

**Comment by kalomaze** [comment]
Install smash version 13.0.1. For future reference, ask the help channel when you have an issue with HDR to make sure if it's an issue on your side.
