### ISSUE TITLE
Toon Link arrow land cancel is missing

### ISSUE THREAD

**Issue by Riah321** [HDR-Development/HewDraw-Remix#596]
Because you can fast fall and it's functionally very similar to Falco laser I can't help but assume that it was also supposed to be land cancellable. It's also terrible as is and land cancelling would make it balanced well.

**Comment by techyCoder81** [comment]
This is a design change because no, it was not outright intended to be land cancellable. However, that might still be fun. Not my call, I should close this as `wontfix` but I won't quite yet until I see discussion on this linked in the comments, from discord.

**Comment by techyCoder81** [comment]
On second thought,  closing this issue. This *design change* was not suggested by a dev or contributor.
