### ISSUE TITLE
Corrin Recovery Fix

### ISSUE THREAD

**Issue by Riah321** [HDR-Development/HewDraw-Remix#597]
Hangs in the air forever when at ledge instead of sweetspotting. Sideways angle kills momentum at the apex even when holding out as far as possible. Down tilt's angle needs to be adjusted from a vaccum hitbox. Up air should be more forgiving on bad DI as it's currently a swiss army.. sword.

**Comment by techyCoder81** [comment]
I'm sorry you feel that way. Don't make balance/design change issues. Bugs only. And issues should be succinct for one specific bug.
