### ISSUE TITLE
yoshi classic mode softlock

### ISSUE THREAD

**Issue by gitgotgud** [HDR-Development/HewDraw-Remix#602]
yoshi's low intensity classic mode final boss seems bugged. i think that ur supposed to fight on the 'floor' sseing as that's where the monster and the items are but as you can see there's a blastzone there. whenever you kill the boss, you just get softlocked on the stage and the blastzones turn off or something, because you just keep falling

https://user-images.githubusercontent.com/105950176/169621567-21ce73c2-a359-4298-a532-c90a13e13626.mp4

**Comment by moklmaru** [comment]
should no longer be relevant due to removed boss stage layouts
