### ISSUE TITLE
Nightly 0.7.3 - Link - Bomb throw has extremely high SDI distance gained

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#610]
When link pulls his bomb and throws it to an opponent, the opponent is able to SDI the bomb a very significant amount of distance. This also works if the opponent throws the bomb to Link as well. Please look at the link below showing a video of the issue. 

https://discord.com/channels/659964948365049887/950979417004466196/978156840414224385

**Comment by Riah321** [comment]
This has been addressed. Please close this issue.
