### ISSUE TITLE
nightly ver. 0.7.3 hdr / training mode visualiser

### ISSUE THREAD

**Issue by gitgotgud** [HDR-Development/HewDraw-Remix#613]
https://user-images.githubusercontent.com/105950176/170122104-bde11f09-f10a-4bf5-b500-e2d181935fb2.mp4

the hitbox visual is appearing over the training mode option overlay

**Comment by BedeScarlet** [comment]
I believe this is unavoidable with the current implementation. It has to render on top of the whole game cause it's an overlay

**Comment by Riah321** [comment]
This is being been addressed. Please close this issue.
