### ISSUE TITLE
Bayo Up Air Crashing Arenas

### ISSUE THREAD

**Issue by thatweirdo321** [HDR-Development/HewDraw-Remix#614]
Hitting a specific part of Bayo Uair seems to disconnect (and corrupt, not allowing you to join back) arenas. I'm not sure which hitbox exactly causes it but most of the time the game froze when I hit a part down and behind Bayo (Near the starting hitbox), it's crashed both with the single hit and the held version. It doesn't always crash either.

**Comment by Riah321** [comment]
This has been addressed. Please close this issue :)
