### ISSUE TITLE
Adding additional taunt sfx for charcaters. 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#619]
A few ideas for taunts to be used with certain moves, similar to PM/P+:

Ike Fsmash, While Charging: "Prepare yourself"

Wolf Sweetspot Wolf Flash: Iconic Howl (It's actually like Brawl's with the JP Voices)

Falcon Knee Sweetspot: "YES!" 

Falco Dair Sweespot: “Piece of cake.” 

Ryu’s Focus Attack full charge: “Your range was one fist short”

ZSamus Down Smash: “You’re mine” or “Be still”

Bayonetta (Unsure of move, maybe Witch Time success or on command with Fthrow?): "Jū-nen hayain da yo!"

Byleth Down B, While Charging: "Allow me to demonstrate." 
-------------------------------------------------------------------------------------------------------------------------------

Could be more in the future, but here's just a few ideas.

**Comment by moklmaru** [comment]
Falcon knee and wolf flash taunt sfx have been added. It is possible that more will be considered in the future and this general idea will be kept in mind, but for the time being this issue will be closed.
