### ISSUE TITLE
Remove Mythra’s Foresight for airdodges, extend activation window and/or advantage frames on grounded Foresight 

### ISSUE THREAD

**Issue by Ashtoric** [HDR-Development/HewDraw-Remix#640]
The new airdodge did not account for mythra’s foresight ability, meaning she 9 times out of 10 will just end up SDing because it acts as a vanilla ultimate airdodge except she goes in absurdly long endlag, coupled with her fallspeed means instant death.

To cover this, and to cover the loss of spotdodge cancelling being removed, extend the advantage or the activation window on Foresight (now just the grounded version).

**Comment by moklmaru** [comment]
Foresight has been removed entirely as of #2235
