### ISSUE TITLE
Standardizing Roll and Spotdodge Data

### ISSUE THREAD

**Issue by MadVillainLordQ** [HDR-Development/HewDraw-Remix#648]
There are many differing roll invincibility data across the cast. The goal here is to standardize all rolls to match roll data to be intangible from frames 4-16 and actionable on frame 33. Spotdodges would be standardized from intangible frames 3-17 and actionable on frame 26. There are special cases like bats within and foresight that have to be examined further.

**Comment by SergioC89** [comment]
> The goal here is to standardize all rolls to match forward roll invincibility which is from frames 4-15. 

Forward rolls are not standardized either, would this alter outlier forward rolls as well?

**Comment by MadVillainLordQ** [comment]
Yes I'll be updating and standardizing all rolls and spot dodges.
