### ISSUE TITLE
Mythra's hair still clips into her back. 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#667]
IDK why it keeps happening, but it's pretty annoying to play Mythra when this happens. Mythra's hair will clip into her back and get stuck for some reason. Happens consistently in normal gameplay and can be easily recreated.

**Comment by kalomaze** [comment]
Problem with every mythra upb animation. Angel said he'd give me the .blends for each when/if he can find them, and once he does, I'll reimport and open a PR

**Comment by moklmaru** [comment]
resolved by #1952
