### ISSUE TITLE
Reduce wavedash lengths globally

### ISSUE THREAD

**Issue by jobrien97** [HDR-Development/HewDraw-Remix#680]
Consistently being able to get Melee perfect angle wavedash lengths has proven to be a bit much. Slight reduction is in order

**Comment by PK-Tone** [comment]
Isn't that one of the things that ought to be fixed by the existence of drift DI?

**Comment by jobrien97** [comment]
> Isn't that one of the things that ought to be fixed by the existence of drift DI?

uh, not sure what this has at all to do with Drift DI

**Comment by PK-Tone** [comment]
I suppose I was making assumptions as to what specific problems you had with the lengths. Since you didn't say.
