### ISSUE TITLE
Wavedashing on platforms with tap jump often causes accidental platdrops

### ISSUE THREAD

**Issue by jobrien97** [HDR-Development/HewDraw-Remix#681]
Rework waveland platdrop stick flick logic

**Comment by techyCoder81** [comment]
this should probably use something like `if stick_y_prev > -0.3 && stick_y < -0.6 {}` instead of `is_flick` since `is_flick` will catch the case of stick is up (for tap jump) -> stick is slightly down and to the side (for wavedash) resulting in a platdrop since that y difference is >0.66.

**Comment by Riah321** [comment]
Fairly sure this has been addressed. If so please close this issue :)
