### ISSUE TITLE
Shorthop/Footstool doesn't work when jumping in special scenarios or for Jump Cancelable Special Moves

### ISSUE THREAD

**Issue by ethangarsia517** [HDR-Development/HewDraw-Remix#684]
The Shorthop/Footstool button does not allow special actions that can normally be jumped or short-hopped out of, to shorthop. These scenarios so far include -
   •Donkey Kong's Cargo Throw
   •Bowser Jr.'s Clown Cart, grounded

It also will not work when using Jump Cancelable specials that can be short-hopped out of using the normal Jump button. It would probably be safe to assume all Cancelable Specials are as such, since nothing that I tested worked, but here is what I tested not to work -
   •Samus and Dark Samus' Charge Shot
   •Fox's Reflector
   •Little Mac's Straight Lunge
   •Ike's Quick Draw
   •Squirtle's Water Gun
   •Lucario's Extreme Speed, grounded
   •Mii Swordfighter's Gale Stab

**Comment by kalomaze** [comment]
This can be closed:
https://github.com/HDR-Development/HewDraw-Remix/pull/683

**Comment by SkewedAskew** [comment]
The shorthop/footstool button also does not allow for grounded floats

**Comment by kalomaze** [comment]
This cannot be closed nvm
