### ISSUE TITLE
Various characters T-Pose when thrown by Kazuya's Gates of Hell

### ISSUE THREAD

**Issue by Trebolt23** [HDR-Development/HewDraw-Remix#697]
On the latest official release, I've noticed that at least two characters default to a T-Pose when thrown by Kazuya's command throw. So far I've only seen this on Bowser and Banjo, but there may be other characters this happens to. Bizarrely, I can't seem to replicate it on Bowser, and I can only get it to happen with Banjo if he's using skins added in the HDR skin pack mod (tested with the pink and purple alts).  
![Super_Smash_Bros _Ultimate_20220616_231239_00](https://user-images.githubusercontent.com/82685843/174238450-29677c6f-0678-4778-9488-bea598ccccb7.jpg)
![Super_Smash_Bros _Ultimate_20220616_231242_00](https://user-images.githubusercontent.com/82685843/174238470-ff09120c-c641-412e-9f35-a6bae4c0ad50.jpg)
![Super_Smash_Bros _Ultimate_20220616_232449_00](https://user-images.githubusercontent.com/82685843/174238474-a35ee73b-980c-41f2-8cc5-8f71228b8d1c.jpg)
![Super_Smash_Bros _Ultimate_20220616_232450_00](https://user-images.githubusercontent.com/82685843/174238476-02b1d8c3-775d-4b79-9b8b-1e94cdbefe54.jpg)

**Comment by kalomaze** [comment]
I think the motion list bins weren't copied for Banjo's alts and one of bowsers alts?
