### ISSUE TITLE
Random CSS crashes

### ISSUE THREAD

**Issue by kalomaze** [HDR-Development/HewDraw-Remix#708]
No clue why this happens but infrequently when on the CSS and selecting multiple characters the game will crash. Happens more often when you have additional controllers or cpus and try setting their characters
![01655592969_01006a800016e000](https://user-images.githubusercontent.com/66376113/174459575-a69abe1f-f3af-4d64-a69b-f378ea3d6f55.jpg)
[01655592969_01006a800016e000.log](https://github.com/HDR-Development/HewDraw-Remix/files/8934484/01655592969_01006a800016e000.log)
.

**Comment by Riah321** [comment]
Can confirm this is real. Having even 2 players connected will crash. If you speedrun the CSS you can get through it before the crash hits in most cases.
