### ISSUE TITLE
Any burry puts the enemy out of reach completely

### ISSUE THREAD

**Issue by O1yyy** [HDR-Development/HewDraw-Remix#71]
Burries currently don't set the enemy in the right amount of Y offset, Krool down throw puts them way underneath the floor, and Wii Fit Trainer Jab3 doesn't put them in the floor at all. 
Other burries untested.

**Comment by black-calculus** [comment]
Sounds almost certainly like an ECB issue, relevant code to address this would likely be here https://github.com/HDR-Development/HewDraw-Remix/blob/dev/fighters/common/src/opff/physics.rs#L24

**Comment by black-calculus** [comment]
Seems the implementation was changed slightly from the old repo, will look into soon
