### ISSUE TITLE
Typo on R.O.B.'s fighter tip screen

### ISSUE THREAD

**Issue by Shubb42** [HDR-Development/HewDraw-Remix#711]
R.O.B.'s tip 3 is about his new fuel gauge. Well, the title spells it "gague," when it's supposed to be gauge.
![20220618_225812](https://user-images.githubusercontent.com/85468102/174465519-c1504034-dd4e-47ff-b187-f612d56022a9.jpg)

**Comment by H3ra-57** [comment]
Fixed
