### ISSUE TITLE
Yoshi's story -- Bowser waveland

### ISSUE THREAD

**Issue by Bitterbub** [HDR-Development/HewDraw-Remix#714]
Bowser has issues wave landing from ledge jump on Yoshi's story. Not sure if it's all skins. I tested so far the dry bones skin and the shadow Bowser skin both weren't acting right. And sometimes they would go right through stage

**Comment by TeamPearson** [comment]
Is he falling inside the stage? Your description is sort of vague.

**Comment by Bitterbub** [comment]
Apologies. Yes, he is. He was falling through ledge, almost the same spot Randall comes out. I kinda wrote the post in a hurry lol
