### ISSUE TITLE
Mii Gunner Fixes / Functionality

### ISSUE THREAD

**Issue by boondoggle621** [HDR-Development/HewDraw-Remix#718]
Flame Pillar endlag doesn't allow for follow-ups unless hit point blank, or from max distance full hop. 
CJK still has the issue where both hits are required to use the actionable on hit function, when it's supposed to be either part independently. Also, I believe there's fair case for it replenishing double jump on hit since it is a move encouraged to be used as a spike / combo tool. There also seems to be some issue with grounded opponents getting hit with the aerial version mid combo getting spiked by the horizontal or top part of the explosion hitbox instead of getting scooped into the kick like normal. Maybe I'm having the person not quite grounded yet on hit? thats all i can think of. 

This is just spitballing here, but Gunner being able to self hit bomb drop so that its a bit of an inbetween of Link Bomb, Dog Can would be pretty cool, as the charge aerials definitely give a lot of room for creativity

**Comment by boondoggle621** [comment]
bump

**Comment by jdipalermo27** [comment]
Shoutouts to this person for giving these suggestions months before i did.
