### ISSUE TITLE
Banjo - remove feather dthrow

### ISSUE THREAD

**Issue by jobrien97** [HDR-Development/HewDraw-Remix#736]
As voiced by others, a bit too weak to justify a feather usage

**Comment by techyCoder81** [comment]
Besides being unclear mechanically, this is also a bury throw which just generically shouldn't exist. ROB for example also has a bury throw, and bury throws are either really garbage, or create weird quasi infinite chaingrabs.

**Comment by Lukayaba** [comment]
Maybe instead of a bury it could be a kill throw? It looks like one
