### ISSUE TITLE
Yoshi Double Jump Snapping To Ground

### ISSUE THREAD

**Issue by Lukayaba** [HDR-Development/HewDraw-Remix#738]
Unsure whether this is intentional. This is most notable when you try and do an instant double jump from the ground, either tap jump followed quickly by a jump button or short hop jump button followed by a jump input. This also causes yoshi to snap to platforms.

**Comment by jobrien97** [comment]
This is called a no-impact landing (NIL). It’s a tech present in PM as well. So, intentional lol
