### ISSUE TITLE
Terry suffers random heart failure when attempting to use EX Burn Knuckle.

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#752]
When Terry attempts to do EX Burn Knuckle, he will slow down immensely in place and be left vulnerable for about 30-40 frames before actually doing the charge forward at normal speed. 

Easily recreated on current nightly with just doing EX Burn Knuckle at any time, air or ground.

**Comment by WuBoytH** [comment]
Would you believe me if I said that was just a part of Terry's PR and you could have reproduced this for weeks?

**Comment by CrossSockDance** [comment]
> Would you believe me if I said that was just a part of Terry's PR and you could have reproduced this for weeks?

Does that imply you knew before it got merged? Either way it’s really annoying and stinky.

**Comment by WuBoytH** [comment]
> > Would you believe me if I said that was just a part of Terry's PR and you could have reproduced this for weeks?
> 
> Does that imply you knew before it got merged? Either way it’s really annoying and stinky.

No, I didn't know, I'm implying that it's just an oversight, since I imagine Calc wanted the *opposite* but just put in the numbers wrong on the FT_MOTION_RATE function.

**Comment by CrossSockDance** [comment]
> > > Would you believe me if I said that was just a part of Terry's PR and you could have reproduced this for weeks?
> > 
> > 
> > Does that imply you knew before it got merged? Either way it’s really annoying and stinky.
> 
> No, I didn't know, I'm implying that it's just an oversight, since I imagine Calc wanted the _opposite_ but just put in the numbers wrong on the FT_MOTION_RATE function.

Understandable. Can it be fixed?
