### ISSUE TITLE
Short hop inputing tilt attack

### ISSUE THREAD

**Issue by Incursio76** [HDR-Development/HewDraw-Remix#776]
When trying to input a short hop if you move too fast in a certain direction it seems to give a tilt attack. From before it would come out right away as it is on the beta but on nightly, you have to wait a sec for it to come out. If you use just the regular jump button though and so a short hop it comes out right away.

**Comment by Riah321** [comment]
To second this, JC grabs will also give tilts if the stick is not neutral. (on nightly)
