### ISSUE TITLE
Item pickup with wavedash broken on latest nightly

### ISSUE THREAD

**Issue by AnalogSSBM** [HDR-Development/HewDraw-Remix#781]
it seems in the recent nightly builds with the updated ecb changes that it is no longer possible to pick up items with a grounded wavedash. 

It seems the only way to do this is to intentionally delay my wavedash until I have been airborne for 2 frames.

I understand if the smoother wavedash takes priority over a niche mechanic like this. 

But it would be amazing if you could keep it in somehow.

-Analog <3

**Comment by O1yyy** [comment]
tweak the title to explicitly mention its broken

"Item pickup with wavedash broken on latest nightly"

**Comment by jobrien97** [comment]
has been fixed

**Comment by jobrien97** [comment]
i lied
