### ISSUE TITLE
Inputting attacks on the same frame as jump breaks inputs.

### ISSUE THREAD

**Issue by Riah321** [HDR-Development/HewDraw-Remix#783]
Inputting up and attack during jump squat (but not on the same frame as jump) will give you up smash no matter if it's tilt or if you've been holding up for 300 frames beforehand. Makes buffing up air incredibly inconsistent. Inputting aerials on the Cstick on the same frame as jump will result in Nair.

**Comment by kalomaze** [comment]
You are buffering jc up smash. I guess the only way to fix this would be to have it so you have to time holding up to buffer a jc upsmash

**Comment by Riah321** [comment]
> You are buffering jc up smash. I guess the only way to fix this would be to have it so you have to time holding up to buffer a jc upsmash 

It happens when holding up long before jumping, and when inputting a tilt input on the stick.
