### ISSUE TITLE
Snake Grenade Movement 

### ISSUE THREAD

**Issue by Jsavagejr** [HDR-Development/HewDraw-Remix#784]
When holding the grenade with Snake, his movements are inverted when walking left and right

**Comment by Lukayaba** [comment]
Adding to this - This doesn't happen when buffering a direction or doing it a second after. this consistently happens when inputting a direction a split second after a grenade pull, and always happens after an attempted dash dance

Neutral B has to be held

**Comment by jobrien97** [comment]
need to reimpl his Walk status
