### ISSUE TITLE
Software crashes when attempting to launch

### ISSUE THREAD

**Issue by Justin-Tiger** [HDR-Development/HewDraw-Remix#786]
There's not much info I can give here. I select play from the HDR launcher, and after a minute of the screen being black it crashes and I'm sent back to the switch menu. I tried 3 times and had the same result each one. On the 2nd attempt I received the thank you for updating ARCropolis pop up, it detected new mods and asked if I wanted to enable them, and then the software crashed

**Comment by kalomaze** [comment]
Ask #help-questions in the Discord to fix your problem, this repository is for tracking issues with the mod, not issues with your install
