### ISSUE TITLE
Neutral B-reverse Window Adjustment

### ISSUE THREAD

**Issue by Kaiokendo661** [HDR-Development/HewDraw-Remix#803]
Currently, the neutral b-reverse window in hdr is only 7 frames while in melee it's a more lenient 20 frames. It's not too bad but it would be nice if the timing was a little less tight than it is at the moment.

**Comment by EonTAS** [comment]
just to make a clarification due to naming scheme, this is referring to the b-turnaround window that occurs before the B input is performed, not the b-reverse window that happens after the input.

**Comment by Kaiokendo661** [comment]
> just to make a clarification due to naming scheme, this is referring to the b-turnaround window that occurs before the B input is performed, not the b-reverse window that happens after the input.

My bad for the phrasing. Thanks for the clarification!
