### ISSUE TITLE
Corrin Pin jump cancel can be interupted by any move if not base skin

### ISSUE THREAD

**Issue by EonTAS** [HDR-Development/HewDraw-Remix#809]
This change was apparently supposed to be applied to every skin but currently only grey male corrin has the nerf applied

intended functionality is jump cancel is un-interuptable at all, but the edit was only made to the base skin

**Comment by jobrien97** [comment]
Need to copy c00 motion list over other slots

**Comment by jobrien97** [comment]
Resolved
