### ISSUE TITLE
Bayo can special/jump cancel out of bullet arts

### ISSUE THREAD

**Issue by EonTAS** [HDR-Development/HewDraw-Remix#814]
https://streamable.com/5czm7m

bullet arts enable the cancel option which feels like its unintended

**Comment by jobrien97** [comment]
Probably have to check for `FIGHTER_BAYONETTA_INSTANCE_WORK_ID_FLAG_SHOOTING_ACTION` in cancel code

**Comment by blu-dev** [comment]
feature not a bug /s
