### ISSUE TITLE
Bayonetta crashes if uair bullet arts used at start of game without hitting anything

### ISSUE THREAD

**Issue by EonTAS** [HDR-Development/HewDraw-Remix#822]
crashes in latest nightly.

Tried other moves and it doesnt crash.
Uair without bullet arts doesnt crash
Happens as long as its the first attack performed by bayo, opponents attacks dont matter and moves without hitboxes dont count.

Crashes in all gamemodes i've tested, so versus, online and training mode

**Comment by blu-dev** [comment]
Thank you for reporting but this is likely an issue with the input visualizer attempting to display hurtboxes for the bullet arts, as they don't crash without it visible.
