### ISSUE TITLE
Grabbing ledge while tethered but without reeling in trumps opponents.

### ISSUE THREAD

**Issue by Riah321** [HDR-Development/HewDraw-Remix#848]
If you're fixing this, please make sure to keep the ability to grab ledge without reeling in! It's very fun and makes tethers more interesting.

**Comment by jobrien97** [comment]
Cannot reproduce this, please check that your build is correct, and post a video

**Comment by Riah321** [comment]
It's been done on the most recent nightly. I'll grab a video in a moment.
