### ISSUE TITLE
Falco shine jump-cancel nerf/lockout?

### ISSUE THREAD

**Issue by zandm7** [HDR-Development/HewDraw-Remix#854]
Not sure if this was intended, but Falco's shine now has some kind of frame lockout for the jump cancel window.

In other words, there's some X amount of frames after the shine comes out that you just can't jump cancel out of. This issue doesn't occur with Fox and AFAIK surfaced sometime in the last week.

**Comment by Riah321** [comment]
What is the lockout window? (in frames)

**Comment by zandm7** [comment]
Didn't measure yet & not home to do so now, but I suspect the issue was introduced with this PR: https://github.com/HDR-Development/HewDraw-Remix/pull/806

**Comment by zandm7** [comment]
Just labbed it out; seems like you have to press jump f4 or later for it to come out. Pressing jump on f1-3 of shine does nothing.

Note that this is not the case with either Fox or Wolf; both of these characters can start a jump cancel on f1 of shine.
