### ISSUE TITLE
Incineroar - Angled grab hitbox not shifting correctly

### ISSUE THREAD

**Issue by black-calculus** [HDR-Development/HewDraw-Remix#86]
Utilizing blujay's hitbox visualizer, grab hitbox does not appear to be angling at all no matter how I hold the stick.

Incineroar's body does angle properly however

**Comment by blu-dev** [comment]
Problem is that we declare ANGLE_GRAB_STICK_Y in three different places lmfao. Working on it now, will have resolution soon.
