### ISSUE TITLE
Little Mac can B-Reverse his Neutral Special and Up Special twice.

### ISSUE THREAD

**Issue by SergioC89** [HDR-Development/HewDraw-Remix#890]
https://streamable.com/xvlctj

**Comment by SergioC89** [comment]
Up B https://streamable.com/7c9zic

**Comment by Riah321** [comment]
Are you sure this isn't just a wavebounce?

**Comment by SergioC89** [comment]
> Are you sure this isn't just a wavebounce?

You can clearly see how he turns twice DURING the move (I intentionally did the first reversal on frame 2). A wavebounce by definition is a turnaround special into a b-reverse, and tor a turnaround special you'd have to input the direction BEFORE the move. It most certainly is two b reverses.
