### ISSUE TITLE
Reimplement Jump Cancel Up Smash

### ISSUE THREAD

**Issue by WuBoytH** [HDR-Development/HewDraw-Remix#918]
In Vanilla, if you enter jumpsquat, release the jump button, and press A while holding Up, you will *always* get an Up Smash. This will be updated so that it will instead only work if the stick has been flicked upwards, instead of needing to be tilted up at all.

**Comment by Riah321** [comment]
When inputting item toss/grab during JS you get grounded item toss instead of a buffered air item toss/zdrop. Otherwise lgtm
