### ISSUE TITLE
New Sonic Side B

### ISSUE THREAD

**Issue by WuBoytH** [HDR-Development/HewDraw-Remix#926]
Instead of it being yet another form of spin dash, it'll be a burst of speed forward that requires dealing damage to even gain access to. Subject to change of course. To be merged into Wish's Sonic PR, whenever that's ready.

This will undergo a two versions:
1. A base version (no animations, just functionality, to test while I ~~procrastinate on~~ make animations)
2. A polished version (add animations, clean up the code)
3. Merge into Wish's Sonic PR.

**Comment by WuBoytH** [comment]
By the way this was tentatively going to be called Boost, however due to the nature of the move not being a sustained running state (It'll be similar in function to PM's Somersault, but with him running instead of spinning), I'm thinking of giving it a different name. Feel free to give suggestions.

**Comment by Detronlegacy** [comment]
If you could find a way to add some kind of >>> effect just underneath sonic you could call it boost pad. 

Unless getting access to the side B is easy like minecart, straight up removing a special doesn't feel great. 
Instead maybe a de-powered version that is slower and not very useful replaces the main version until you hit the requirements
