### ISSUE TITLE
Ivysaur uses CrashBeam! It's Super Effective! 

### ISSUE THREAD

**Issue by CrossSockDance** [HDR-Development/HewDraw-Remix#935]
Ivysaur still crashes the game unfortunately. To be honest I'm not really sure when it happens, feels similar to Link crashing when exiting tumble long ago. But sometimes I'll just hit them with a single tilt as they switch as well and they crash. It's been about three crashes in the past week with them now.

Sorry I don't have more stuff to show.

**Comment by Jetsplit** [comment]
In my experience it can happen with any of the 3 Pokémon, with or without them being separated using the Character Expansion mod from Gamebanana. Fingers crossed someone smarter than me can figure it out soon!
