### ISSUE TITLE
Mechakoopa walking loop shortened on right portion of Dracula's Castle

### ISSUE THREAD

**Issue by RealAwwa** [HDR-Development/HewDraw-Remix#943]
Deploying mechakoopa on the right section of Dracula's castle prevents it from walking past that section of that stage, causing it to walk back and forth from a cutoff point to the right ledge. Circled the portion it gets stuck on in the LVD file screenshot here:

![Capture](https://user-images.githubusercontent.com/111538010/185494386-52d9f8b0-97ef-4327-b155-cfbacfd6df47.PNG)

**Comment by moklmaru** [comment]
confirmed that this no longer occurs on the current version of dracula's castle

https://github.com/HDR-Development/HewDraw-Remix/assets/16338870/9ecedbb6-20b9-4d1e-a6b5-84381bf5d1ae
