### ISSUE TITLE
Clear Footstool when Shield Dropping.

### ISSUE THREAD

**Issue by Wish325** [HDR-Development/HewDraw-Remix#957]
Issue name is pretty self explanatory. 

There seems to be an unintended issue with the taunt method of shield dropping. Sometimes when you shielddrop with the taunt button, it will also buffer a footstool if the opponent is close. This is almost always detrimental.

**Comment by jobrien97** [comment]
Turns out this is not actually an issue with our logic. Nintendo's dpad hardware is just finicky in general, as a slight movement may roll the dpad enough to trigger a new taunt input in another direction. Just try not to move the dpad as much when shielddropping
