### ISSUE TITLE
F-tilt Tilt Stick going into grab from wavedash

### ISSUE THREAD

**Issue by yoonikoo** [HDR-Development/HewDraw-Remix#974]
Upon doing a frame perfect wavedash into f-tilt tilt attack, X character will go into a grab instead of performing a f-tilt tilt attack.

**Comment by jobrien97** [comment]
This only happens if you still have shield held near the end of your wavedash. Shield + tilt stick = shield + A = grab macro. Just let go of shield earlier, or release shield before inputting buffered attack
