### ISSUE TITLE
Holding Down + flick Cstick in a different direction auto fastfalls

### ISSUE THREAD

**Issue by EonTAS** [HDR-Development/HewDraw-Remix#989]
This is just a general issue with cstick being a stick macro and has been a "bug" since brawl, but with shielddropping with stick being very feasible this becomes annoying since shielddrop cstick aerial is almost always going to fastfall on its own. 

Its also just a generally annoying thing thatd be nice to fix

happens coz cstick overrides for a frame, and then the next frame the game sees the stick re-enter being straight down so it'll fastfall

**Comment by SergioC89** [comment]
Duplicate issue. #221  Please close
